/*
  ORIENTACAO — DDL tabelas TB_* (SQL Server / T-SQL)
  Ajuste o banco alvo antes de executar:
    USE [TESTE];   -- ou o database da sua instalação

  Integração com a API Node existente (mapDataRepository / mapDataService):
    - Hoje: leitura de TESTE..COORDENADAS_AGENCIAS e TESTE..COORDENADAS_LOJAS (lon/lat).
    - Evolução: criar VIEW ou alterar o repositório para ler TB_MAPA_PONTO_REGIONAL / TB_ESCADA_COMERCIAL
      mapeando colunas LONGITUDE/LATITUDE para o JSON esperado pelo front (mapDataApi.SqlMapPoint).

  Join com lojas no warehouse (sem FK cross-database):
    SELECT e.*, l.CHAVE_LOJA
    FROM dbo.TB_ESCADA_COMERCIAL AS e
    INNER JOIN DATAWAREHOUSE.dbo.TB_ESTR_LOJAS AS l
      ON l.COD_AG_RELACIONAMENTO = e.COD_AG;
    (Tipos de COD_AG / COD_AG_RELACIONAMENTO devem coincidir — INT ou VARCHAR conforme seu DW.)
*/

-- USE [TESTE];
-- GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* Ordem de drop: dependentes primeiro */
IF OBJECT_ID(N'dbo.TB_SERIE_PRODUTO_PERIODO', N'U') IS NOT NULL DROP TABLE dbo.TB_SERIE_PRODUTO_PERIODO;
IF OBJECT_ID(N'dbo.TB_METRICA_UF_PRODUTO_SUB_MES', N'U') IS NOT NULL DROP TABLE dbo.TB_METRICA_UF_PRODUTO_SUB_MES;
IF OBJECT_ID(N'dbo.TB_METRICA_UF_PRODUTO_MES', N'U') IS NOT NULL DROP TABLE dbo.TB_METRICA_UF_PRODUTO_MES;
IF OBJECT_ID(N'dbo.TB_METRICA_UF_RESUMO_MES', N'U') IS NOT NULL DROP TABLE dbo.TB_METRICA_UF_RESUMO_MES;
IF OBJECT_ID(N'dbo.TB_METRICA_GEO_PRODUTO_MES', N'U') IS NOT NULL DROP TABLE dbo.TB_METRICA_GEO_PRODUTO_MES;
IF OBJECT_ID(N'dbo.TB_MAPA_PONTO_REGIONAL', N'U') IS NOT NULL DROP TABLE dbo.TB_MAPA_PONTO_REGIONAL;
IF OBJECT_ID(N'dbo.TB_ESCADA_COMERCIAL', N'U') IS NOT NULL DROP TABLE dbo.TB_ESCADA_COMERCIAL;
IF OBJECT_ID(N'dbo.TB_MUNICIPIO', N'U') IS NOT NULL DROP TABLE dbo.TB_MUNICIPIO;
IF OBJECT_ID(N'dbo.TB_PRODUTO_SUB', N'U') IS NOT NULL DROP TABLE dbo.TB_PRODUTO_SUB;
IF OBJECT_ID(N'dbo.TB_PRODUTO', N'U') IS NOT NULL DROP TABLE dbo.TB_PRODUTO;
IF OBJECT_ID(N'dbo.TB_UF', N'U') IS NOT NULL DROP TABLE dbo.TB_UF;
GO

CREATE TABLE dbo.TB_UF (
  UF_SIGLA     CHAR(2)      NOT NULL,
  UF_NOME      NVARCHAR(80) NULL,
  CONSTRAINT PK_TB_UF PRIMARY KEY (UF_SIGLA)
);
GO

CREATE TABLE dbo.TB_MUNICIPIO (
  MUNICIPIO_ID   BIGINT        NOT NULL IDENTITY(1,1),
  IBGE_CODIGO    INT           NOT NULL,
  NOME           NVARCHAR(120) NOT NULL,
  UF_SIGLA       CHAR(2)       NOT NULL,
  CONSTRAINT PK_TB_MUNICIPIO PRIMARY KEY (MUNICIPIO_ID),
  CONSTRAINT UQ_TB_MUNICIPIO_IBGE_UF UNIQUE (IBGE_CODIGO, UF_SIGLA),
  CONSTRAINT FK_TB_MUNICIPIO_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA)
);
GO

CREATE TABLE dbo.TB_PRODUTO (
  PRODUTO_ID     VARCHAR(32)   NOT NULL,
  NOME_EXIBICAO  NVARCHAR(120) NOT NULL,
  CONSTRAINT PK_TB_PRODUTO PRIMARY KEY (PRODUTO_ID)
);
GO

CREATE TABLE dbo.TB_PRODUTO_SUB (
  SUBPRODUTO_ID  VARCHAR(64)   NOT NULL,
  PRODUTO_ID     VARCHAR(32)   NOT NULL,
  NOME           NVARCHAR(120) NOT NULL,
  VALOR_LEGENDA  NVARCHAR(80)  NULL,
  CONSTRAINT PK_TB_PRODUTO_SUB PRIMARY KEY (SUBPRODUTO_ID),
  CONSTRAINT FK_TB_PRODUTO_SUB_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID)
);
GO

/* Uma linha por agência — tabela de relacionamento COD_AG x hierarquia comercial */
CREATE TABLE dbo.TB_ESCADA_COMERCIAL (
  DIRE_REG            INT            NOT NULL,
  DIR_REGIONAL        NVARCHAR(200)  NOT NULL,
  COD_GER_REG         INT            NOT NULL,
  GER_REGIONAL        NVARCHAR(200)  NOT NULL,
  COD_GER_AREA        INT            NULL,
  DESC_GERENCIA_AREA  NVARCHAR(200)  NOT NULL,
  COD_COORD           INT            NULL,
  DESC_COORDENACAO    NVARCHAR(200)  NOT NULL,
  COD_SUPERVISAO      INT            NULL,
  DESC_SUPERVISAO     NVARCHAR(200)  NOT NULL,
  COD_AG              INT            NOT NULL,
  NOME_AG             NVARCHAR(200)  NOT NULL,
  CONSTRAINT PK_TB_ESCADA_COMERCIAL PRIMARY KEY (COD_AG)
);
GO

CREATE INDEX IX_TB_ESCADA_DIRE_REG ON dbo.TB_ESCADA_COMERCIAL (DIRE_REG);
CREATE INDEX IX_TB_ESCADA_COD_GER_REG ON dbo.TB_ESCADA_COMERCIAL (COD_GER_REG);
CREATE INDEX IX_TB_ESCADA_COD_GER_AREA ON dbo.TB_ESCADA_COMERCIAL (COD_GER_AREA);
CREATE INDEX IX_TB_ESCADA_COD_COORD ON dbo.TB_ESCADA_COMERCIAL (COD_COORD);
CREATE INDEX IX_TB_ESCADA_COD_SUPERVISAO ON dbo.TB_ESCADA_COMERCIAL (COD_SUPERVISAO);
GO

CREATE TABLE dbo.TB_MAPA_PONTO_REGIONAL (
  PONTO_ID     VARCHAR(64)   NOT NULL,
  KIND         VARCHAR(16)   NOT NULL,
  NOME         NVARCHAR(200) NOT NULL,
  UF_SIGLA     CHAR(2)       NULL,
  LONGITUDE    FLOAT         NOT NULL,
  LATITUDE     FLOAT         NOT NULL,
  CONSTRAINT PK_TB_MAPA_PONTO_REGIONAL PRIMARY KEY (PONTO_ID),
  CONSTRAINT FK_TB_MAPA_PONTO_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA)
);
GO

CREATE TABLE dbo.TB_METRICA_UF_RESUMO_MES (
  UF_SIGLA               CHAR(2)        NOT NULL,
  ANO_REF                  SMALLINT       NOT NULL,
  MES_REF                  TINYINT        NOT NULL,
  QTD_AGENCIAS             INT            NOT NULL,
  QTD_PAS                  INT            NOT NULL,
  QTD_PRACAS_PRESENCAS     INT            NOT NULL,
  QTD_LOJAS                INT            NOT NULL,
  QTD_LOJAS_ATIVAS         INT            NOT NULL,
  QTD_LOJAS_ATIVAS_VAREJO         INT     NOT NULL CONSTRAINT DF_TB_UF_RES_ATV_VAREJO DEFAULT (0),
  QTD_LOJAS_ATIVAS_GRANDES_REDES  INT     NOT NULL CONSTRAINT DF_TB_UF_RES_ATV_GR DEFAULT (0),
  QTD_LOJAS_ATIVAS_EXCLUSIVO      INT     NOT NULL CONSTRAINT DF_TB_UF_RES_ATV_EX DEFAULT (0),
  QTD_LOJAS_ATIVAS_CASAS_BAHIA    INT     NOT NULL CONSTRAINT DF_TB_UF_RES_ATV_CB DEFAULT (0),
  CONSTRAINT PK_TB_METRICA_UF_RESUMO_MES PRIMARY KEY (UF_SIGLA, ANO_REF, MES_REF),
  CONSTRAINT FK_TB_METRICA_UF_RESUMO_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA)
);
GO

CREATE TABLE dbo.TB_METRICA_UF_PRODUTO_MES (
  UF_SIGLA            CHAR(2)         NOT NULL,
  ANO_REF             SMALLINT        NOT NULL,
  MES_REF             TINYINT         NOT NULL,
  PRODUTO_ID          VARCHAR(32)     NOT NULL,
  PRODUCAO_VALOR      DECIMAL(18,2)   NOT NULL,
  QTD_LOJAS           INT             NOT NULL,
  QTD_LOJAS_ATIVAS    INT             NOT NULL,
  VARIACAO_PCT        DECIMAL(9,2)    NOT NULL,
  PARTICIPACAO_PCT    DECIMAL(9,2)    NOT NULL,
  STATUS_SEMANTICO    VARCHAR(12)     NULL,
  INSIGHT_DESTAQUE    NVARCHAR(500)   NULL,
  CONSTRAINT PK_TB_METRICA_UF_PRODUTO_MES PRIMARY KEY (UF_SIGLA, ANO_REF, MES_REF, PRODUTO_ID),
  CONSTRAINT FK_TB_METRICA_UF_PROD_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA),
  CONSTRAINT FK_TB_METRICA_UF_PROD_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID)
);
GO

CREATE TABLE dbo.TB_METRICA_UF_PRODUTO_SUB_MES (
  UF_SIGLA           CHAR(2)        NOT NULL,
  ANO_REF             SMALLINT       NOT NULL,
  MES_REF             TINYINT        NOT NULL,
  PRODUTO_ID          VARCHAR(32)    NOT NULL,
  SUBPRODUTO_ID       VARCHAR(64)    NOT NULL,
  QTD_LOJAS           INT            NOT NULL,
  QTD_PRODUCAO        INT            NULL,
  PRODUCAO_VALOR      DECIMAL(18,2)  NOT NULL,
  CONSTRAINT PK_TB_METRICA_UF_PRODUTO_SUB_MES PRIMARY KEY (UF_SIGLA, ANO_REF, MES_REF, PRODUTO_ID, SUBPRODUTO_ID),
  CONSTRAINT FK_TB_METRICA_UF_SUB_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA),
  CONSTRAINT FK_TB_METRICA_UF_SUB_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID),
  CONSTRAINT FK_TB_METRICA_UF_SUB_SUB FOREIGN KEY (SUBPRODUTO_ID) REFERENCES dbo.TB_PRODUTO_SUB (SUBPRODUTO_ID)
);
GO

CREATE TABLE dbo.TB_SERIE_PRODUTO_PERIODO (
  UF_SIGLA           CHAR(2)        NOT NULL,
  PRODUTO_ID         VARCHAR(32)    NOT NULL,
  PERIODO_TIPO       VARCHAR(8)     NOT NULL,
  ORDEM              TINYINT        NOT NULL,
  LABEL              NVARCHAR(32)   NOT NULL,
  VALOR_ATUAL_MIL    DECIMAL(12,4)  NOT NULL,
  VALOR_ANTERIOR_MIL DECIMAL(12,4)  NOT NULL,
  REFERENCIA_FIM     DATE           NOT NULL,
  CONSTRAINT PK_TB_SERIE_PRODUTO_PERIODO PRIMARY KEY (UF_SIGLA, PRODUTO_ID, PERIODO_TIPO, ORDEM, REFERENCIA_FIM),
  CONSTRAINT FK_TB_SERIE_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA),
  CONSTRAINT FK_TB_SERIE_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID),
  CONSTRAINT CK_TB_SERIE_PERIODO_TIPO CHECK (PERIODO_TIPO IN (N'7D', N'30D', N'3M', N'12M'))
);
GO

CREATE INDEX IX_TB_SERIE_LOOKUP ON dbo.TB_SERIE_PRODUTO_PERIODO (UF_SIGLA, PRODUTO_ID, PERIODO_TIPO, REFERENCIA_FIM);
GO

CREATE TABLE dbo.TB_METRICA_GEO_PRODUTO_MES (
  TIPO_GEO        VARCHAR(3)      NOT NULL,
  UF_SIGLA        CHAR(2)         NOT NULL,
  IBGE_MUNICIPIO  INT             NULL,
  NOME_MATCH      NVARCHAR(200)   NOT NULL,
  PRODUTO_ID      VARCHAR(32)     NOT NULL,
  ANO_REF         SMALLINT        NOT NULL,
  MES_REF         TINYINT         NOT NULL,
  QTD_LOJAS       INT             NOT NULL,
  PRODUCAO_VALOR  DECIMAL(18,2)   NOT NULL,
  VARIACAO_PCT    DECIMAL(9,2)    NOT NULL,
  CONSTRAINT PK_TB_METRICA_GEO_PRODUTO_MES PRIMARY KEY (TIPO_GEO, UF_SIGLA, PRODUTO_ID, ANO_REF, MES_REF, NOME_MATCH),
  CONSTRAINT FK_TB_METRICA_GEO_UF FOREIGN KEY (UF_SIGLA) REFERENCES dbo.TB_UF (UF_SIGLA),
  CONSTRAINT FK_TB_METRICA_GEO_PROD FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID),
  CONSTRAINT CK_TB_METRICA_GEO_TIPO CHECK (TIPO_GEO IN (N'UF', N'MUN'))
);
GO

CREATE INDEX IX_TB_METRICA_GEO_MUN_IBGE ON dbo.TB_METRICA_GEO_PRODUTO_MES (TIPO_GEO, IBGE_MUNICIPIO, PRODUTO_ID, ANO_REF, MES_REF)
  WHERE IBGE_MUNICIPIO IS NOT NULL;
GO

PRINT N'DDL concluído: TB_UF, TB_MUNICIPIO, TB_PRODUTO, TB_PRODUTO_SUB, TB_ESCADA_COMERCIAL, TB_MAPA_PONTO_REGIONAL, TB_METRICA_* , TB_SERIE_PRODUTO_PERIODO.';
GO
