/*
  ORIENTACAO — suporte a métricas do ExpressoStatePanel por município selecionado
  Objetivo: permitir leitura por COD_IBGE quando o usuário clicar em município no mapa.

  Execute após 01_DDL_TABELAS.sql.
*/

-- USE [TESTE];
-- GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES (
    COD_IBGE          INT            NOT NULL,
    UF_SIGLA          CHAR(2)        NOT NULL,
    NOME_MUNICIPIO    NVARCHAR(120)  NOT NULL,
    ANO_REF           SMALLINT       NOT NULL,
    MES_REF           TINYINT        NOT NULL,
    PRODUTO_ID        VARCHAR(32)    NOT NULL,
    PRODUCAO_VALOR    DECIMAL(18,2)  NOT NULL,
    QTD_LOJAS         INT            NOT NULL,
    QTD_LOJAS_ATIVAS  INT            NOT NULL,
    VARIACAO_PCT      DECIMAL(9,2)   NOT NULL,
    PARTICIPACAO_PCT  DECIMAL(9,2)   NOT NULL,
    STATUS_SEMANTICO  VARCHAR(12)    NULL,
    INSIGHT_DESTAQUE  NVARCHAR(500)  NULL,
    CONSTRAINT PK_TB_METRICA_MUNICIPIO_PRODUTO_MES
      PRIMARY KEY (COD_IBGE, ANO_REF, MES_REF, PRODUTO_ID),
    CONSTRAINT FK_TB_METRICA_MUN_PROD_PRODUTO
      FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO (PRODUTO_ID)
  );
END;
GO

IF OBJECT_ID(N'dbo.TB_METRICA_MUNICIPIO_RESUMO_MES', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.TB_METRICA_MUNICIPIO_RESUMO_MES (
    COD_IBGE               INT           NOT NULL,
    UF_SIGLA               CHAR(2)       NOT NULL,
    NOME_MUNICIPIO         NVARCHAR(120) NOT NULL,
    ANO_REF                SMALLINT      NOT NULL,
    MES_REF                TINYINT       NOT NULL,
    QTD_AGENCIAS           INT           NOT NULL,
    QTD_PAS                INT           NOT NULL,
    QTD_PRACAS_PRESENCAS   INT           NOT NULL,
    QTD_LOJAS              INT           NOT NULL,
    QTD_LOJAS_ATIVAS       INT           NOT NULL,
    CONSTRAINT PK_TB_METRICA_MUNICIPIO_RESUMO_MES
      PRIMARY KEY (COD_IBGE, ANO_REF, MES_REF)
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_TB_METRICA_MUN_PROD_UF_MES'
    AND object_id = OBJECT_ID(N'dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES')
)
BEGIN
  CREATE INDEX IX_TB_METRICA_MUN_PROD_UF_MES
    ON dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES (UF_SIGLA, ANO_REF, MES_REF, PRODUTO_ID, COD_IBGE);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_TB_METRICA_MUN_RES_UF_MES'
    AND object_id = OBJECT_ID(N'dbo.TB_METRICA_MUNICIPIO_RESUMO_MES')
)
BEGIN
  CREATE INDEX IX_TB_METRICA_MUN_RES_UF_MES
    ON dbo.TB_METRICA_MUNICIPIO_RESUMO_MES (UF_SIGLA, ANO_REF, MES_REF, COD_IBGE);
END;
GO

/*
  Mapeamento inicial (carga derivada do que já existe):
  - Fonte: TB_METRICA_GEO_PRODUTO_MES (TIPO_GEO='MUN') + TB_METRICA_UF_PRODUTO_MES
  - Inclui COD_IBGE para lookup do município selecionado no mapa.
*/
;WITH base AS (
  SELECT
    g.IBGE_MUNICIPIO AS COD_IBGE,
    g.UF_SIGLA,
    g.NOME_MATCH AS NOME_MUNICIPIO,
    g.ANO_REF,
    g.MES_REF,
    g.PRODUTO_ID,
    g.PRODUCAO_VALOR,
    g.QTD_LOJAS,
    CAST(ROUND(g.QTD_LOJAS * 0.78, 0) AS INT) AS QTD_LOJAS_ATIVAS,
    g.VARIACAO_PCT,
    CASE
      WHEN SUM(g.PRODUCAO_VALOR) OVER (PARTITION BY g.IBGE_MUNICIPIO, g.ANO_REF, g.MES_REF) = 0 THEN 0
      ELSE CAST(
        g.PRODUCAO_VALOR * 100.0
        / SUM(g.PRODUCAO_VALOR) OVER (PARTITION BY g.IBGE_MUNICIPIO, g.ANO_REF, g.MES_REF)
      AS DECIMAL(9,2))
    END AS PARTICIPACAO_PCT
  FROM dbo.TB_METRICA_GEO_PRODUTO_MES AS g
  WHERE g.TIPO_GEO = 'MUN'
    AND g.IBGE_MUNICIPIO IS NOT NULL
),
enriched AS (
  SELECT
    b.*,
    CASE
      WHEN b.VARIACAO_PCT <= -8 OR (b.VARIACAO_PCT <= -4 AND b.PARTICIPACAO_PCT >= 28) THEN 'CRITICO'
      WHEN b.VARIACAO_PCT < 0 THEN 'ATENCAO'
      ELSE 'SAUDAVEL'
    END AS STATUS_SEMANTICO
  FROM base AS b
)
MERGE dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES AS tgt
USING enriched AS src
ON tgt.COD_IBGE = src.COD_IBGE
 AND tgt.ANO_REF = src.ANO_REF
 AND tgt.MES_REF = src.MES_REF
 AND tgt.PRODUTO_ID = src.PRODUTO_ID
WHEN MATCHED THEN
  UPDATE SET
    tgt.UF_SIGLA = src.UF_SIGLA,
    tgt.NOME_MUNICIPIO = src.NOME_MUNICIPIO,
    tgt.PRODUCAO_VALOR = src.PRODUCAO_VALOR,
    tgt.QTD_LOJAS = src.QTD_LOJAS,
    tgt.QTD_LOJAS_ATIVAS = src.QTD_LOJAS_ATIVAS,
    tgt.VARIACAO_PCT = src.VARIACAO_PCT,
    tgt.PARTICIPACAO_PCT = src.PARTICIPACAO_PCT,
    tgt.STATUS_SEMANTICO = src.STATUS_SEMANTICO,
    tgt.INSIGHT_DESTAQUE = CONCAT(
      src.NOME_MUNICIPIO, N' • ', src.PRODUTO_ID,
      N' com variação de ', CAST(src.VARIACAO_PCT AS NVARCHAR(30)), N'% no município.'
    )
WHEN NOT MATCHED BY TARGET THEN
  INSERT (
    COD_IBGE, UF_SIGLA, NOME_MUNICIPIO, ANO_REF, MES_REF, PRODUTO_ID,
    PRODUCAO_VALOR, QTD_LOJAS, QTD_LOJAS_ATIVAS, VARIACAO_PCT, PARTICIPACAO_PCT,
    STATUS_SEMANTICO, INSIGHT_DESTAQUE
  )
  VALUES (
    src.COD_IBGE, src.UF_SIGLA, src.NOME_MUNICIPIO, src.ANO_REF, src.MES_REF, src.PRODUTO_ID,
    src.PRODUCAO_VALOR, src.QTD_LOJAS, src.QTD_LOJAS_ATIVAS, src.VARIACAO_PCT, src.PARTICIPACAO_PCT,
    src.STATUS_SEMANTICO, CONCAT(
      src.NOME_MUNICIPIO, N' • ', src.PRODUTO_ID,
      N' com variação de ', CAST(src.VARIACAO_PCT AS NVARCHAR(30)), N'% no município.'
    )
  );
GO

;WITH resumo AS (
  SELECT
    COD_IBGE,
    UF_SIGLA,
    NOME_MUNICIPIO,
    ANO_REF,
    MES_REF,
    COUNT(DISTINCT CASE WHEN PRODUTO_ID = 'consignado' THEN COD_IBGE END) AS QTD_AGENCIAS,
    CAST(ROUND(MAX(QTD_LOJAS) * 0.55, 0) AS INT) AS QTD_PAS,
    CAST(ROUND(MAX(QTD_LOJAS) * 0.45, 0) AS INT) AS QTD_PRACAS_PRESENCAS,
    MAX(QTD_LOJAS) AS QTD_LOJAS,
    MAX(QTD_LOJAS_ATIVAS) AS QTD_LOJAS_ATIVAS
  FROM dbo.TB_METRICA_MUNICIPIO_PRODUTO_MES
  GROUP BY COD_IBGE, UF_SIGLA, NOME_MUNICIPIO, ANO_REF, MES_REF
)
MERGE dbo.TB_METRICA_MUNICIPIO_RESUMO_MES AS tgt
USING resumo AS src
ON tgt.COD_IBGE = src.COD_IBGE
 AND tgt.ANO_REF = src.ANO_REF
 AND tgt.MES_REF = src.MES_REF
WHEN MATCHED THEN
  UPDATE SET
    tgt.UF_SIGLA = src.UF_SIGLA,
    tgt.NOME_MUNICIPIO = src.NOME_MUNICIPIO,
    tgt.QTD_AGENCIAS = src.QTD_AGENCIAS,
    tgt.QTD_PAS = src.QTD_PAS,
    tgt.QTD_PRACAS_PRESENCAS = src.QTD_PRACAS_PRESENCAS,
    tgt.QTD_LOJAS = src.QTD_LOJAS,
    tgt.QTD_LOJAS_ATIVAS = src.QTD_LOJAS_ATIVAS
WHEN NOT MATCHED BY TARGET THEN
  INSERT (
    COD_IBGE, UF_SIGLA, NOME_MUNICIPIO, ANO_REF, MES_REF,
    QTD_AGENCIAS, QTD_PAS, QTD_PRACAS_PRESENCAS, QTD_LOJAS, QTD_LOJAS_ATIVAS
  )
  VALUES (
    src.COD_IBGE, src.UF_SIGLA, src.NOME_MUNICIPIO, src.ANO_REF, src.MES_REF,
    src.QTD_AGENCIAS, src.QTD_PAS, src.QTD_PRACAS_PRESENCAS, src.QTD_LOJAS, src.QTD_LOJAS_ATIVAS
  );
GO

PRINT N'OK: Tabelas municipais para StatePanel criadas/atualizadas com COD_IBGE.';
GO
