USE [TESTE];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.ROTEIROS_MAPA', N'U') IS NULL
    THROW 51000, 'Tabela TESTE.dbo.ROTEIROS_MAPA não encontrada.', 1;

IF OBJECT_ID(N'dbo.ROTEIRO_PARADAS_MAPA', N'U') IS NULL
    THROW 51001, 'Tabela TESTE.dbo.ROTEIRO_PARADAS_MAPA não encontrada. O ambiente pode estar usando outro nome.', 1;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'STATUS_GESTAO') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD STATUS_GESTAO VARCHAR(20) NOT NULL
                CONSTRAINT DF_ROTEIROS_MAPA_STATUS_GESTAO DEFAULT ('ATIVO') WITH VALUES;
    END;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'PRIORIDADE') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD PRIORIDADE VARCHAR(10) NOT NULL
                CONSTRAINT DF_ROTEIROS_MAPA_PRIORIDADE DEFAULT ('NORMAL') WITH VALUES;
    END;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'ORIENTACAO') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD ORIENTACAO NVARCHAR(1000) NULL;
    END;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'ATUALIZADO_EM_UTC') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD ATUALIZADO_EM_UTC DATETIME2(3) NOT NULL
                CONSTRAINT DF_ROTEIROS_MAPA_ATUALIZADO_EM_UTC
                DEFAULT (SYSUTCDATETIME()) WITH VALUES;
    END;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'ATUALIZADO_POR') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD ATUALIZADO_POR INT NULL;
    END;

    IF COL_LENGTH(N'dbo.ROTEIROS_MAPA', N'VERSAO_LINHA') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIROS_MAPA
            ADD VERSAO_LINHA ROWVERSION;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'ATIVO') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD ATIVO BIT NOT NULL
                CONSTRAINT DF_ROTEIRO_PARADAS_MAPA_ATIVO DEFAULT (1) WITH VALUES;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'CANCELADO_EM_UTC') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD CANCELADO_EM_UTC DATETIME2(3) NULL;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'CANCELADO_POR') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD CANCELADO_POR INT NULL;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'ATUALIZADO_EM_UTC') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD ATUALIZADO_EM_UTC DATETIME2(3) NOT NULL
                CONSTRAINT DF_ROTEIRO_PARADAS_MAPA_ATUALIZADO_EM_UTC
                DEFAULT (SYSUTCDATETIME()) WITH VALUES;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'ATUALIZADO_POR') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD ATUALIZADO_POR INT NULL;
    END;

    IF COL_LENGTH(N'dbo.ROTEIRO_PARADAS_MAPA', N'VERSAO_LINHA') IS NULL
    BEGIN
        ALTER TABLE dbo.ROTEIRO_PARADAS_MAPA
            ADD VERSAO_LINHA ROWVERSION;
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE parent_object_id = OBJECT_ID(N'dbo.ROTEIROS_MAPA')
          AND name = N'CK_ROTEIROS_MAPA_STATUS_GESTAO'
    )
    BEGIN
        EXEC(N'
            ALTER TABLE dbo.ROTEIROS_MAPA WITH CHECK
                ADD CONSTRAINT CK_ROTEIROS_MAPA_STATUS_GESTAO
                CHECK (STATUS_GESTAO IN (''ATIVO'', ''CANCELADO'', ''SUBSTITUIDO''));
        ');
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE parent_object_id = OBJECT_ID(N'dbo.ROTEIROS_MAPA')
          AND name = N'CK_ROTEIROS_MAPA_PRIORIDADE'
    )
    BEGIN
        EXEC(N'
            ALTER TABLE dbo.ROTEIROS_MAPA WITH CHECK
                ADD CONSTRAINT CK_ROTEIROS_MAPA_PRIORIDADE
                CHECK (PRIORIDADE IN (''BAIXA'', ''NORMAL'', ''ALTA'', ''CRITICA''));
        ');
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.ROTEIROS_MAPA')
          AND name = N'IX_ROTEIROS_MAPA_RESP_STATUS_DATA'
    )
    BEGIN
        EXEC(N'
            CREATE INDEX IX_ROTEIROS_MAPA_RESP_STATUS_DATA
                ON dbo.ROTEIROS_MAPA
                    (COD_FUNC_RESPONSAVEL, STATUS_GESTAO, DATA_ROTEIRO DESC)
                INCLUDE (ID, NOME, PRIORIDADE, CHAVE_SUPERVISAO, VERSAO);
        ');
    END;

    -- Dá suporte à FK composta da visita, impedindo que PARADA e ROTEIRO
    -- sejam associados de forma inconsistente.
    IF NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.ROTEIRO_PARADAS_MAPA')
          AND name = N'UX_ROTEIRO_PARADAS_MAPA_ID_ROTEIRO'
    )
    BEGIN
        CREATE UNIQUE INDEX UX_ROTEIRO_PARADAS_MAPA_ID_ROTEIRO
            ON dbo.ROTEIRO_PARADAS_MAPA (ID, ROTEIRO_ID);
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.ROTEIRO_PARADAS_MAPA')
          AND name = N'IX_ROTEIRO_PARADAS_MAPA_LOJA'
    )
    BEGIN
        CREATE INDEX IX_ROTEIRO_PARADAS_MAPA_LOJA
            ON dbo.ROTEIRO_PARADAS_MAPA (CHAVE_LOJA, ROTEIRO_ID)
            INCLUDE (ID, ORDEM, STATUS, COD_AG, NOME);
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.ROTEIRO_PARADAS_MAPA')
          AND name = N'IX_ROTEIRO_PARADAS_MAPA_ROTEIRO_ATIVO'
    )
    BEGIN
        EXEC(N'
            CREATE INDEX IX_ROTEIRO_PARADAS_MAPA_ROTEIRO_ATIVO
                ON dbo.ROTEIRO_PARADAS_MAPA (ROTEIRO_ID, ATIVO, ORDEM)
                INCLUDE (ID, CHAVE_LOJA, STATUS, HORARIO, NOME);
        ');
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
