USE [TESTE];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

IF OBJECT_ID(N'dbo.ROTEIROS_MAPA', N'U') IS NULL
    THROW 51000, 'Execute primeiro 00_ajustes_roteiros_existentes.sql.', 1;

IF OBJECT_ID(N'dbo.ROTEIRO_PARADAS_MAPA', N'U') IS NULL
    THROW 51001, 'Execute primeiro 00_ajustes_roteiros_existentes.sql.', 1;
GO

/* -------------------------------------------------------------------------
   Recria as tabelas deste script: drop em ordem de dependência e create.
   Dados de visitas/notificações nestas tabelas serão apagados.
   ------------------------------------------------------------------------- */

IF OBJECT_ID(N'dbo.TR_TB_HISTORICO_VISITA_APPEND_ONLY', N'TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TB_HISTORICO_VISITA_APPEND_ONLY;
IF OBJECT_ID(N'dbo.TR_TB_AUDITORIA_ROTEIRO_APPEND_ONLY', N'TR') IS NOT NULL
    DROP TRIGGER dbo.TR_TB_AUDITORIA_ROTEIRO_APPEND_ONLY;
GO

IF OBJECT_ID(N'dbo.TB_HISTORICO_VISITA', N'U') IS NOT NULL DROP TABLE dbo.TB_HISTORICO_VISITA;
IF OBJECT_ID(N'dbo.TB_AUDITORIA_ROTEIRO', N'U') IS NOT NULL DROP TABLE dbo.TB_AUDITORIA_ROTEIRO;
IF OBJECT_ID(N'dbo.TB_VISITA_ACOMPANHAMENTO', N'U') IS NOT NULL DROP TABLE dbo.TB_VISITA_ACOMPANHAMENTO;
IF OBJECT_ID(N'dbo.TB_NOTIFICACAO_USUARIO', N'U') IS NOT NULL DROP TABLE dbo.TB_NOTIFICACAO_USUARIO;
IF OBJECT_ID(N'dbo.TB_NOTIFICACAO', N'U') IS NOT NULL DROP TABLE dbo.TB_NOTIFICACAO;
IF OBJECT_ID(N'dbo.TB_NOTIFICACAO_REGRA', N'U') IS NOT NULL DROP TABLE dbo.TB_NOTIFICACAO_REGRA;
IF OBJECT_ID(N'dbo.TB_VISITA_REAGENDAMENTO', N'U') IS NOT NULL DROP TABLE dbo.TB_VISITA_REAGENDAMENTO;
IF OBJECT_ID(N'dbo.TB_VISITA_PRODUTO', N'U') IS NOT NULL DROP TABLE dbo.TB_VISITA_PRODUTO;
IF OBJECT_ID(N'dbo.TB_VISITA_CHECKIN', N'U') IS NOT NULL DROP TABLE dbo.TB_VISITA_CHECKIN;
IF OBJECT_ID(N'dbo.TB_VISITA_TRATATIVA', N'U') IS NOT NULL DROP TABLE dbo.TB_VISITA_TRATATIVA;
IF OBJECT_ID(N'dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO', N'U') IS NOT NULL DROP TABLE dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO;
IF OBJECT_ID(N'dbo.TB_PRODUTO_FOCO', N'U') IS NOT NULL DROP TABLE dbo.TB_PRODUTO_FOCO;
IF OBJECT_ID(N'dbo.TB_JOB_EXECUCAO', N'U') IS NOT NULL DROP TABLE dbo.TB_JOB_EXECUCAO;
IF OBJECT_ID(N'dbo.TB_JOB_CONTROLE', N'U') IS NOT NULL DROP TABLE dbo.TB_JOB_CONTROLE;
IF OBJECT_ID(N'dbo.TB_EVENTO_OUTBOX', N'U') IS NOT NULL DROP TABLE dbo.TB_EVENTO_OUTBOX;
IF OBJECT_ID(N'dbo.TB_COMANDO_IDEMPOTENCIA', N'U') IS NOT NULL DROP TABLE dbo.TB_COMANDO_IDEMPOTENCIA;
GO


/* -------------------------------------------------------------------------
   Catálogo e regras de produto
   ------------------------------------------------------------------------- */

CREATE TABLE dbo.TB_PRODUTO_FOCO (
    ID                       INT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_PRODUTO_FOCO PRIMARY KEY,
    CODIGO                   VARCHAR(40) NOT NULL,
    NOME                     NVARCHAR(100) NOT NULL,
    DESCRICAO                NVARCHAR(500) NULL,
    ESTRATEGIA_VALIDACAO     VARCHAR(60) NULL,
    ATIVO                    BIT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_FOCO_ATIVO DEFAULT (1),
    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_FOCO_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR               INT NOT NULL,
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_FOCO_ATUALIZADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR           INT NOT NULL,
    VERSAO_LINHA             ROWVERSION,
    CONSTRAINT UQ_TB_PRODUTO_FOCO_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_TB_PRODUTO_FOCO_CODIGO
        CHECK (CODIGO <> '' AND CODIGO NOT LIKE '%[^A-Z0-9_]%')
);

CREATE INDEX IX_TB_PRODUTO_FOCO_ATIVO_NOME
    ON dbo.TB_PRODUTO_FOCO (ATIVO, NOME)
    INCLUDE (CODIGO, ESTRATEGIA_VALIDACAO);
GO

CREATE TABLE dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO (
    ID                           BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_PRODUTO_REGRA_ACOMPANHAMENTO PRIMARY KEY,
    PRODUTO_ID                   INT NOT NULL,
    TIPO_OPORTUNIDADE            VARCHAR(50) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_TIPO_OPORTUNIDADE DEFAULT ('GERAL'),
    PRAZO_DIAS                   SMALLINT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_PRAZO_DIAS DEFAULT (4),
    DIAS_UTEIS                   BIT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_DIAS_UTEIS DEFAULT (0),
    HORA_EXECUCAO_LOCAL          TIME(0) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_HORA DEFAULT ('09:00:00'),
    MAX_TENTATIVAS_TECNICAS      SMALLINT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_MAX_TENTATIVAS DEFAULT (5),
    INTERVALO_REAVALIACAO_HORAS  SMALLINT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_INTERVALO DEFAULT (24),
    MAX_ADIAMENTOS_USUARIO       SMALLINT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_MAX_ADIAMENTOS DEFAULT (3),
    ESTRATEGIA_VALIDACAO         VARCHAR(60) NOT NULL,
    PARAMETROS_JSON              NVARCHAR(MAX) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_PARAMETROS DEFAULT (N'{}'),
    VERSAO_REGRA                 INT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_VERSAO DEFAULT (1),
    VIGENCIA_INICIO              DATE NOT NULL,
    VIGENCIA_FIM                 DATE NULL,
    ATIVO                        BIT NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_ATIVO DEFAULT (1),
    CRIADO_EM_UTC                DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR                   INT NOT NULL,
    ATUALIZADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_PRODUTO_REGRA_ATUALIZADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR               INT NOT NULL,
    VERSAO_LINHA                 ROWVERSION,
    CONSTRAINT FK_TB_PRODUTO_REGRA_PRODUTO
        FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO_FOCO(ID),
    CONSTRAINT CK_TB_PRODUTO_REGRA_PRAZO
        CHECK (PRAZO_DIAS BETWEEN 0 AND 365),
    CONSTRAINT CK_TB_PRODUTO_REGRA_TENTATIVAS
        CHECK (MAX_TENTATIVAS_TECNICAS BETWEEN 1 AND 50),
    CONSTRAINT CK_TB_PRODUTO_REGRA_INTERVALO
        CHECK (INTERVALO_REAVALIACAO_HORAS BETWEEN 1 AND 8760),
    CONSTRAINT CK_TB_PRODUTO_REGRA_ADIAMENTOS
        CHECK (MAX_ADIAMENTOS_USUARIO BETWEEN 0 AND 50),
    CONSTRAINT CK_TB_PRODUTO_REGRA_VERSAO
        CHECK (VERSAO_REGRA > 0),
    CONSTRAINT CK_TB_PRODUTO_REGRA_VIGENCIA
        CHECK (VIGENCIA_FIM IS NULL OR VIGENCIA_FIM >= VIGENCIA_INICIO),
    CONSTRAINT CK_TB_PRODUTO_REGRA_PARAMETROS_JSON
        CHECK (ISJSON(PARAMETROS_JSON) = 1),
    CONSTRAINT UQ_TB_PRODUTO_REGRA_VERSAO
        UNIQUE (PRODUTO_ID, TIPO_OPORTUNIDADE, VERSAO_REGRA)
);

CREATE UNIQUE INDEX UX_TB_PRODUTO_REGRA_ATIVA
    ON dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO (PRODUTO_ID, TIPO_OPORTUNIDADE)
    WHERE ATIVO = 1;

CREATE INDEX IX_TB_PRODUTO_REGRA_VIGENCIA
    ON dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO
        (PRODUTO_ID, TIPO_OPORTUNIDADE, VIGENCIA_INICIO, VIGENCIA_FIM)
    INCLUDE (ATIVO, PRAZO_DIAS, DIAS_UTEIS, ESTRATEGIA_VALIDACAO);
GO

/* -------------------------------------------------------------------------
   Visita e tratativas
   ------------------------------------------------------------------------- */

CREATE TABLE dbo.TB_VISITA_TRATATIVA (
    ID                           BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_VISITA_TRATATIVA PRIMARY KEY,
    PARADA_ROTEIRO_ID            BIGINT NOT NULL,
    ROTEIRO_ID                   UNIQUEIDENTIFIER NOT NULL,
    VISITA_ORIGEM_ID             BIGINT NULL,
    SEQUENCIA                    SMALLINT NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_SEQUENCIA DEFAULT (1),
    EH_ATUAL                     BIT NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_EH_ATUAL DEFAULT (1),

    CHAVE_LOJA                   NVARCHAR(100) NOT NULL,
    NOME_LOJA                    NVARCHAR(250) NOT NULL,
    COD_AG                       NVARCHAR(20) NULL,
    CHAVE_SUPERVISAO             INT NOT NULL,
    ENDERECO                     NVARCHAR(500) NULL,

    COD_FUNC_RESPONSAVEL         INT NOT NULL,
    NOME_RESPONSAVEL             NVARCHAR(150) NOT NULL,
    COD_FUNC_CRIADOR             INT NOT NULL,
    NOME_CRIADOR                 NVARCHAR(150) NOT NULL,

    DATA_PLANEJADA               DATE NOT NULL,
    HORARIO_PLANEJADO            TIME(0) NULL,
    FUSO_HORARIO                 VARCHAR(64) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_FUSO DEFAULT ('America/Sao_Paulo'),
    PRIORIDADE                   VARCHAR(10) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_PRIORIDADE DEFAULT ('NORMAL'),
    ORIENTACAO                   NVARCHAR(1000) NULL,

    STATUS                       VARCHAR(20) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_STATUS DEFAULT ('PENDENTE'),
    RESPOSTA_REALIZACAO          VARCHAR(20) NULL,
    RESULTADO_COMERCIAL          VARCHAR(30) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_RESULTADO DEFAULT ('SEM_RESULTADO'),
    DATA_VISITA                  DATE NULL,
    INICIO_EM_UTC                DATETIME2(3) NULL,
    TERMINO_EM_UTC               DATETIME2(3) NULL,
    MOTIVO_NAO_REALIZACAO        VARCHAR(40) NULL,
    JUSTIFICATIVA_NAO_REALIZACAO NVARCHAR(1000) NULL,
    OBSERVACAO_GERAL             NVARCHAR(2000) NULL,
    NECESSITA_RETORNO            BIT NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_NECESSITA_RETORNO DEFAULT (0),
    DATA_PREVISTA_RETORNO        DATE NULL,

    SALVO_PARCIAL_EM_UTC         DATETIME2(3) NULL,
    FINALIZADA_EM_UTC            DATETIME2(3) NULL,
    FINALIZADA_POR               INT NULL,
    CRIADO_EM_UTC                DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR                   INT NOT NULL,
    ATUALIZADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_TRATATIVA_ATUALIZADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR               INT NOT NULL,
    VERSAO_LINHA                 ROWVERSION,

    CONSTRAINT FK_TB_VISITA_TRATATIVA_PARADA_ROTEIRO
        FOREIGN KEY (PARADA_ROTEIRO_ID, ROTEIRO_ID)
        REFERENCES dbo.ROTEIRO_PARADAS_MAPA(ID, ROTEIRO_ID),
    CONSTRAINT FK_TB_VISITA_TRATATIVA_ROTEIRO
        FOREIGN KEY (ROTEIRO_ID) REFERENCES dbo.ROTEIROS_MAPA(ID),
    CONSTRAINT FK_TB_VISITA_TRATATIVA_ORIGEM
        FOREIGN KEY (VISITA_ORIGEM_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),

    CONSTRAINT CK_TB_VISITA_TRATATIVA_SEQUENCIA
        CHECK (SEQUENCIA > 0),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_STATUS
        CHECK (STATUS IN (
            'PENDENTE', 'EM_ANDAMENTO', 'REALIZADA',
            'NAO_REALIZADA', 'REAGENDADA', 'CANCELADA'
        )),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_RESPOSTA
        CHECK (
            RESPOSTA_REALIZACAO IS NULL OR
            RESPOSTA_REALIZACAO IN ('SIM', 'NAO', 'REAGENDADA')
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_PRIORIDADE
        CHECK (PRIORIDADE IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_RESULTADO
        CHECK (RESULTADO_COMERCIAL IN (
            'SEM_RESULTADO', 'APRESENTADO', 'INTERESSE', 'PROPOSTA',
            'CONTRATADO', 'TRANSACIONOU', 'SEM_INTERESSE',
            'SEM_OPORTUNIDADE', 'OUTRO'
        )),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_PERIODO
        CHECK (
            INICIO_EM_UTC IS NULL OR TERMINO_EM_UTC IS NULL OR
            TERMINO_EM_UTC >= INICIO_EM_UTC
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_OUTRO
        CHECK (
            MOTIVO_NAO_REALIZACAO <> 'OUTRO' OR
            NULLIF(LTRIM(RTRIM(JUSTIFICATIVA_NAO_REALIZACAO)), N'') IS NOT NULL
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_REALIZADA
        CHECK (
            STATUS <> 'REALIZADA' OR
            (
                RESPOSTA_REALIZACAO = 'SIM' AND
                DATA_VISITA IS NOT NULL AND
                INICIO_EM_UTC IS NOT NULL AND
                FINALIZADA_EM_UTC IS NOT NULL AND
                FINALIZADA_POR IS NOT NULL
            )
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_NAO_REALIZADA
        CHECK (
            STATUS <> 'NAO_REALIZADA' OR
            (
                RESPOSTA_REALIZACAO = 'NAO' AND
                MOTIVO_NAO_REALIZACAO IS NOT NULL AND
                FINALIZADA_EM_UTC IS NOT NULL AND
                FINALIZADA_POR IS NOT NULL
            )
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_REAGENDADA
        CHECK (
            STATUS <> 'REAGENDADA' OR
            (
                RESPOSTA_REALIZACAO = 'REAGENDADA' AND
                FINALIZADA_EM_UTC IS NOT NULL AND
                FINALIZADA_POR IS NOT NULL AND
                EH_ATUAL = 0
            )
        ),
    CONSTRAINT CK_TB_VISITA_TRATATIVA_CANCELADA
        CHECK (
            STATUS <> 'CANCELADA' OR
            (
                FINALIZADA_EM_UTC IS NOT NULL AND
                FINALIZADA_POR IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX UX_TB_VISITA_TRATATIVA_PARADA_SEQUENCIA
    ON dbo.TB_VISITA_TRATATIVA (PARADA_ROTEIRO_ID, SEQUENCIA);

CREATE UNIQUE INDEX UX_TB_VISITA_TRATATIVA_PARADA_ATUAL
    ON dbo.TB_VISITA_TRATATIVA (PARADA_ROTEIRO_ID)
    WHERE EH_ATUAL = 1;

CREATE INDEX IX_TB_VISITA_TRATATIVA_RESP_STATUS_DATA
    ON dbo.TB_VISITA_TRATATIVA
        (COD_FUNC_RESPONSAVEL, STATUS, DATA_PLANEJADA, HORARIO_PLANEJADO)
    INCLUDE (ID, ROTEIRO_ID, PARADA_ROTEIRO_ID, CHAVE_LOJA, PRIORIDADE, EH_ATUAL);

CREATE INDEX IX_TB_VISITA_TRATATIVA_ROTEIRO_STATUS
    ON dbo.TB_VISITA_TRATATIVA (ROTEIRO_ID, STATUS, SEQUENCIA)
    INCLUDE (ID, PARADA_ROTEIRO_ID, CHAVE_LOJA, DATA_PLANEJADA, EH_ATUAL);

CREATE INDEX IX_TB_VISITA_TRATATIVA_LOJA_DATA
    ON dbo.TB_VISITA_TRATATIVA (CHAVE_LOJA, DATA_PLANEJADA DESC)
    INCLUDE (ID, STATUS, COD_FUNC_RESPONSAVEL, ROTEIRO_ID);

CREATE INDEX IX_TB_VISITA_TRATATIVA_SUP_DATA
    ON dbo.TB_VISITA_TRATATIVA
        (CHAVE_SUPERVISAO, DATA_PLANEJADA, STATUS)
    INCLUDE (ID, COD_FUNC_RESPONSAVEL, CHAVE_LOJA, PRIORIDADE);
GO

CREATE TABLE dbo.TB_VISITA_CHECKIN (
    ID                           BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_VISITA_CHECKIN PRIMARY KEY,
    VISITA_ID                    BIGINT NOT NULL,
    TIPO                         VARCHAR(10) NOT NULL
        CONSTRAINT DF_TB_VISITA_CHECKIN_TIPO DEFAULT ('CHECKIN'),
    DATA_HORA_DISPOSITIVO_UTC    DATETIME2(3) NOT NULL,
    DATA_HORA_SERVIDOR_UTC       DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_CHECKIN_SERVIDOR DEFAULT (SYSUTCDATETIME()),
    FUSO_OFFSET_MINUTOS          SMALLINT NOT NULL,
    COD_FUNC_USUARIO             INT NOT NULL,
    LATITUDE                     DECIMAL(9,6) NULL,
    LONGITUDE                    DECIMAL(9,6) NULL,
    PRECISAO_METROS              DECIMAL(10,2) NULL,
    LATITUDE_LOJA                DECIMAL(9,6) NULL,
    LONGITUDE_LOJA               DECIMAL(9,6) NULL,
    DISTANCIA_METROS             DECIMAL(10,2) NULL,
    RAIO_PERMITIDO_METROS        DECIMAL(10,2) NULL,
    STATUS_VALIDACAO             VARCHAR(30) NOT NULL,
    ORIGEM                       VARCHAR(20) NOT NULL,
    JUSTIFICATIVA_EXCECAO        NVARCHAR(1000) NULL,
    DISPOSITIVO_EVENTO_ID        VARCHAR(100) NOT NULL,
    RECEBIDO_COM_ATRASO          BIT NOT NULL
        CONSTRAINT DF_TB_VISITA_CHECKIN_ATRASO DEFAULT (0),
    VALIDADO_EM_UTC              DATETIME2(3) NULL,
    VALIDADO_POR                 INT NULL,
    CRIADO_EM_UTC                DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_CHECKIN_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    VERSAO_LINHA                 ROWVERSION,

    CONSTRAINT FK_TB_VISITA_CHECKIN_VISITA
        FOREIGN KEY (VISITA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT UQ_TB_VISITA_CHECKIN_DISPOSITIVO_EVENTO
        UNIQUE (DISPOSITIVO_EVENTO_ID),
    CONSTRAINT CK_TB_VISITA_CHECKIN_TIPO
        CHECK (TIPO IN ('CHECKIN', 'CHECKOUT')),
    CONSTRAINT CK_TB_VISITA_CHECKIN_OFFSET
        CHECK (FUSO_OFFSET_MINUTOS BETWEEN -840 AND 840),
    CONSTRAINT CK_TB_VISITA_CHECKIN_COORDENADAS
        CHECK (
            (LATITUDE IS NULL AND LONGITUDE IS NULL) OR
            (
                LATITUDE IS NOT NULL AND
                LONGITUDE IS NOT NULL AND
                LATITUDE BETWEEN -90 AND 90 AND
                LONGITUDE BETWEEN -180 AND 180
            )
        ),
    CONSTRAINT CK_TB_VISITA_CHECKIN_COORDENADAS_LOJA
        CHECK (
            (LATITUDE_LOJA IS NULL AND LONGITUDE_LOJA IS NULL) OR
            (
                LATITUDE_LOJA IS NOT NULL AND
                LONGITUDE_LOJA IS NOT NULL AND
                LATITUDE_LOJA BETWEEN -90 AND 90 AND
                LONGITUDE_LOJA BETWEEN -180 AND 180
            )
        ),
    CONSTRAINT CK_TB_VISITA_CHECKIN_METRICAS
        CHECK (
            (PRECISAO_METROS IS NULL OR PRECISAO_METROS >= 0) AND
            (DISTANCIA_METROS IS NULL OR DISTANCIA_METROS >= 0) AND
            (RAIO_PERMITIDO_METROS IS NULL OR RAIO_PERMITIDO_METROS >= 0)
        ),
    CONSTRAINT CK_TB_VISITA_CHECKIN_STATUS
        CHECK (STATUS_VALIDACAO IN (
            'VALIDADO', 'FORA_DO_RAIO', 'SEM_GEOLOCALIZACAO',
            'PENDENTE_VALIDACAO', 'REJEITADO', 'NAO_APLICAVEL'
        )),
    CONSTRAINT CK_TB_VISITA_CHECKIN_ORIGEM
        CHECK (ORIGEM IN ('GPS', 'REDE', 'MANUAL', 'OFFLINE', 'SISTEMA')),
    CONSTRAINT CK_TB_VISITA_CHECKIN_EXCECAO
        CHECK (
            STATUS_VALIDACAO NOT IN ('FORA_DO_RAIO', 'SEM_GEOLOCALIZACAO') OR
            NULLIF(LTRIM(RTRIM(JUSTIFICATIVA_EXCECAO)), N'') IS NOT NULL
        )
);

CREATE UNIQUE INDEX UX_TB_VISITA_CHECKIN_VISITA_TIPO
    ON dbo.TB_VISITA_CHECKIN (VISITA_ID, TIPO);

CREATE INDEX IX_TB_VISITA_CHECKIN_USUARIO_DATA
    ON dbo.TB_VISITA_CHECKIN (COD_FUNC_USUARIO, DATA_HORA_SERVIDOR_UTC DESC)
    INCLUDE (VISITA_ID, TIPO, STATUS_VALIDACAO, DISTANCIA_METROS);

CREATE INDEX IX_TB_VISITA_CHECKIN_VALIDACAO
    ON dbo.TB_VISITA_CHECKIN (STATUS_VALIDACAO, DATA_HORA_SERVIDOR_UTC)
    INCLUDE (VISITA_ID, COD_FUNC_USUARIO, DISTANCIA_METROS);
GO

CREATE TABLE dbo.TB_VISITA_PRODUTO (
    ID                               BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_VISITA_PRODUTO PRIMARY KEY,
    VISITA_ID                        BIGINT NOT NULL,
    PRODUTO_ID                       INT NOT NULL,
    REGRA_ACOMPANHAMENTO_ID          BIGINT NULL,
    CODIGO_PRODUTO_SNAPSHOT          VARCHAR(40) NOT NULL,
    NOME_PRODUTO_SNAPSHOT            NVARCHAR(100) NOT NULL,
    TIPO_OPORTUNIDADE                VARCHAR(50) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_TIPO_OPORTUNIDADE DEFAULT ('GERAL'),
    OPORTUNIDADE_SNAPSHOT_JSON       NVARCHAR(MAX) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_OPORTUNIDADE DEFAULT (N'{}'),

    STATUS_TRATATIVA                 VARCHAR(20) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_STATUS_TRATATIVA DEFAULT ('PENDENTE'),
    RESULTADO_VISITA                 VARCHAR(30) NULL,
    OBSERVACAO                       NVARCHAR(2000) NULL,
    JUSTIFICATIVA_NAO_ABORDADO       NVARCHAR(1000) NULL,
    NECESSITA_ACOMPANHAMENTO         BIT NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_ACOMPANHAMENTO DEFAULT (0),
    STATUS_ACOMPANHAMENTO            VARCHAR(30) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_STATUS_ACOMP DEFAULT ('NAO_APLICAVEL'),
    ATIVO                            BIT NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_ATIVO DEFAULT (1),
    REMOVIDO_EM_UTC                  DATETIME2(3) NULL,
    REMOVIDO_POR                     INT NULL,

    BASELINE_JSON                    NVARCHAR(MAX) NULL,
    BASELINE_EM_UTC                  DATETIME2(3) NULL,
    EVIDENCIA_ATUAL_JSON             NVARCHAR(MAX) NULL,
    ULTIMA_VERIFICACAO_EM_UTC        DATETIME2(3) NULL,
    PROXIMA_VERIFICACAO_EM_UTC       DATETIME2(3) NULL,
    EVOLUCAO_DETECTADA_EM_UTC        DATETIME2(3) NULL,
    RESUMO_EVIDENCIA                 NVARCHAR(1000) NULL,

    TENTATIVAS_TECNICAS              SMALLINT NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_TENTATIVAS DEFAULT (0),
    BLOQUEADO_ATE_EM_UTC             DATETIME2(3) NULL,
    BLOQUEADO_POR_WORKER             VARCHAR(100) NULL,
    ULTIMO_ERRO_TECNICO              NVARCHAR(2000) NULL,

    TRATADO_EM_UTC                   DATETIME2(3) NULL,
    TRATADO_POR                      INT NULL,
    CRIADO_EM_UTC                    DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR                       INT NOT NULL,
    ATUALIZADO_EM_UTC                DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_PRODUTO_ATUALIZADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR                   INT NOT NULL,
    VERSAO_LINHA                     ROWVERSION,

    CONSTRAINT FK_TB_VISITA_PRODUTO_VISITA
        FOREIGN KEY (VISITA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT FK_TB_VISITA_PRODUTO_PRODUTO
        FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.TB_PRODUTO_FOCO(ID),
    CONSTRAINT FK_TB_VISITA_PRODUTO_REGRA
        FOREIGN KEY (REGRA_ACOMPANHAMENTO_ID)
        REFERENCES dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO(ID),
    CONSTRAINT UQ_TB_VISITA_PRODUTO_VISITA_PRODUTO
        UNIQUE (VISITA_ID, PRODUTO_ID),
    CONSTRAINT CK_TB_VISITA_PRODUTO_OPORTUNIDADE_JSON
        CHECK (ISJSON(OPORTUNIDADE_SNAPSHOT_JSON) = 1),
    CONSTRAINT CK_TB_VISITA_PRODUTO_BASELINE_JSON
        CHECK (BASELINE_JSON IS NULL OR ISJSON(BASELINE_JSON) = 1),
    CONSTRAINT CK_TB_VISITA_PRODUTO_EVIDENCIA_JSON
        CHECK (EVIDENCIA_ATUAL_JSON IS NULL OR ISJSON(EVIDENCIA_ATUAL_JSON) = 1),
    CONSTRAINT CK_TB_VISITA_PRODUTO_STATUS_TRATATIVA
        CHECK (STATUS_TRATATIVA IN ('PENDENTE', 'TRATADO', 'NAO_ABORDADO')),
    CONSTRAINT CK_TB_VISITA_PRODUTO_RESULTADO
        CHECK (
            RESULTADO_VISITA IS NULL OR
            RESULTADO_VISITA IN (
                'APRESENTADO', 'INTERESSE', 'PROPOSTA', 'CONTRATADO',
                'TRANSACIONOU', 'SEM_INTERESSE', 'SEM_OPORTUNIDADE',
                'NAO_ABORDADO', 'OUTRO'
            )
        ),
    CONSTRAINT CK_TB_VISITA_PRODUTO_STATUS_ACOMPANHAMENTO
        CHECK (STATUS_ACOMPANHAMENTO IN (
            'NAO_APLICAVEL', 'AGUARDANDO_EVOLUCAO', 'EVOLUIDO',
            'EVOLUCAO_CONFIRMADA', 'SEM_EVOLUCAO',
            'ACOMPANHAMENTO_PENDENTE', 'REAGENDADO',
            'SEM_CONTINUIDADE', 'ENCERRADO'
        )),
    CONSTRAINT CK_TB_VISITA_PRODUTO_NAO_ABORDADO
        CHECK (
            STATUS_TRATATIVA <> 'NAO_ABORDADO' OR
            (
                RESULTADO_VISITA = 'NAO_ABORDADO' AND
                NULLIF(LTRIM(RTRIM(JUSTIFICATIVA_NAO_ABORDADO)), N'') IS NOT NULL
            )
        ),
    CONSTRAINT CK_TB_VISITA_PRODUTO_TRATADO
        CHECK (
            STATUS_TRATATIVA <> 'TRATADO' OR
            (
                RESULTADO_VISITA IS NOT NULL AND
                TRATADO_EM_UTC IS NOT NULL AND
                TRATADO_POR IS NOT NULL
            )
        ),
    CONSTRAINT CK_TB_VISITA_PRODUTO_TENTATIVAS
        CHECK (TENTATIVAS_TECNICAS >= 0),
    CONSTRAINT CK_TB_VISITA_PRODUTO_REMOCAO
        CHECK (
            ATIVO = 1 OR
            (REMOVIDO_EM_UTC IS NOT NULL AND REMOVIDO_POR IS NOT NULL)
        )
);

CREATE INDEX IX_TB_VISITA_PRODUTO_VISITA_STATUS
    ON dbo.TB_VISITA_PRODUTO (VISITA_ID, STATUS_TRATATIVA)
    INCLUDE (ID, PRODUTO_ID, STATUS_ACOMPANHAMENTO, NECESSITA_ACOMPANHAMENTO);

CREATE INDEX IX_TB_VISITA_PRODUTO_VERIFICACAO
    ON dbo.TB_VISITA_PRODUTO
        (STATUS_ACOMPANHAMENTO, PROXIMA_VERIFICACAO_EM_UTC)
    INCLUDE (ID, VISITA_ID, PRODUTO_ID, REGRA_ACOMPANHAMENTO_ID, TENTATIVAS_TECNICAS)
    WHERE PROXIMA_VERIFICACAO_EM_UTC IS NOT NULL;

CREATE INDEX IX_TB_VISITA_PRODUTO_PRODUTO_STATUS
    ON dbo.TB_VISITA_PRODUTO (PRODUTO_ID, STATUS_ACOMPANHAMENTO, ATUALIZADO_EM_UTC)
    INCLUDE (ID, VISITA_ID, RESULTADO_VISITA);
GO

CREATE TABLE dbo.TB_VISITA_REAGENDAMENTO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_VISITA_REAGENDAMENTO PRIMARY KEY,
    VISITA_ORIGEM_ID         BIGINT NOT NULL,
    VISITA_NOVA_ID           BIGINT NOT NULL,
    DATA_ANTERIOR            DATE NOT NULL,
    HORARIO_ANTERIOR         TIME(0) NULL,
    NOVA_DATA                DATE NOT NULL,
    NOVO_HORARIO             TIME(0) NULL,
    MOTIVO                   VARCHAR(40) NOT NULL,
    JUSTIFICATIVA            NVARCHAR(1000) NULL,
    ORIENTACAO               NVARCHAR(1000) NULL,
    PRIORIDADE               VARCHAR(10) NOT NULL,
    REAGENDADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_REAGENDAMENTO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    REAGENDADO_POR           INT NOT NULL,
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,

    CONSTRAINT FK_TB_VISITA_REAGENDAMENTO_ORIGEM
        FOREIGN KEY (VISITA_ORIGEM_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT FK_TB_VISITA_REAGENDAMENTO_NOVA
        FOREIGN KEY (VISITA_NOVA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT UQ_TB_VISITA_REAGENDAMENTO_ORIGEM UNIQUE (VISITA_ORIGEM_ID),
    CONSTRAINT UQ_TB_VISITA_REAGENDAMENTO_NOVA UNIQUE (VISITA_NOVA_ID),
    CONSTRAINT CK_TB_VISITA_REAGENDAMENTO_VISITAS
        CHECK (VISITA_ORIGEM_ID <> VISITA_NOVA_ID),
    CONSTRAINT CK_TB_VISITA_REAGENDAMENTO_DATA
        CHECK (NOVA_DATA >= DATA_ANTERIOR),
    CONSTRAINT CK_TB_VISITA_REAGENDAMENTO_MOTIVO
        CHECK (MOTIVO IN (
            'REAGENDADA_COM_CLIENTE', 'RESPONSAVEL_AUSENTE',
            'ESTABELECIMENTO_FECHADO', 'PROBLEMA_DESLOCAMENTO', 'OUTRO'
        )),
    CONSTRAINT CK_TB_VISITA_REAGENDAMENTO_OUTRO
        CHECK (
            MOTIVO <> 'OUTRO' OR
            NULLIF(LTRIM(RTRIM(JUSTIFICATIVA)), N'') IS NOT NULL
        ),
    CONSTRAINT CK_TB_VISITA_REAGENDAMENTO_PRIORIDADE
        CHECK (PRIORIDADE IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA'))
);

CREATE INDEX IX_TB_VISITA_REAGENDAMENTO_NOVA_DATA
    ON dbo.TB_VISITA_REAGENDAMENTO (NOVA_DATA, NOVO_HORARIO)
    INCLUDE (VISITA_ORIGEM_ID, VISITA_NOVA_ID, REAGENDADO_POR);
GO

/* -------------------------------------------------------------------------
   Regras e ocorrências de notificação
   ------------------------------------------------------------------------- */

CREATE TABLE dbo.TB_NOTIFICACAO_REGRA (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_NOTIFICACAO_REGRA PRIMARY KEY,
    CODIGO                   VARCHAR(60) NOT NULL,
    VERSAO_REGRA             INT NOT NULL,
    TIPO_NOTIFICACAO         VARCHAR(60) NOT NULL,
    EVENTO_GATILHO           VARCHAR(80) NOT NULL,
    PRIORIDADE_PADRAO        VARCHAR(10) NOT NULL,
    ATRASO_INICIAL_MINUTOS   INT NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_ATRASO DEFAULT (0),
    EXPIRACAO_MINUTOS        INT NULL,
    TEMPLATE_TITULO          NVARCHAR(200) NOT NULL,
    TEMPLATE_MENSAGEM        NVARCHAR(1000) NOT NULL,
    POLITICA_REPETICAO_JSON  NVARCHAR(MAX) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_REPETICAO DEFAULT (N'{}'),
    POLITICA_ESCALADA_JSON   NVARCHAR(MAX) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_ESCALADA DEFAULT (N'{}'),
    ACOES_JSON               NVARCHAR(MAX) NOT NULL,
    CANAIS_JSON              NVARCHAR(MAX) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_CANAIS DEFAULT (N'["IN_APP"]'),
    VIGENCIA_INICIO          DATE NOT NULL,
    VIGENCIA_FIM             DATE NULL,
    ATIVO                    BIT NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_ATIVO DEFAULT (1),
    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR               INT NOT NULL,
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_REGRA_ATUALIZADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR           INT NOT NULL,
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT UQ_TB_NOTIFICACAO_REGRA_CODIGO_VERSAO
        UNIQUE (CODIGO, VERSAO_REGRA),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_VERSAO
        CHECK (VERSAO_REGRA > 0),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_PRIORIDADE
        CHECK (PRIORIDADE_PADRAO IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_ATRASO
        CHECK (ATRASO_INICIAL_MINUTOS >= 0),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_EXPIRACAO
        CHECK (EXPIRACAO_MINUTOS IS NULL OR EXPIRACAO_MINUTOS > 0),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_VIGENCIA
        CHECK (VIGENCIA_FIM IS NULL OR VIGENCIA_FIM >= VIGENCIA_INICIO),
    CONSTRAINT CK_TB_NOTIFICACAO_REGRA_JSON
        CHECK (
            ISJSON(POLITICA_REPETICAO_JSON) = 1 AND
            ISJSON(POLITICA_ESCALADA_JSON) = 1 AND
            ISJSON(ACOES_JSON) = 1 AND
            ISJSON(CANAIS_JSON) = 1
        )
);

CREATE UNIQUE INDEX UX_TB_NOTIFICACAO_REGRA_ATIVA
    ON dbo.TB_NOTIFICACAO_REGRA (CODIGO)
    WHERE ATIVO = 1;

CREATE INDEX IX_TB_NOTIFICACAO_REGRA_EVENTO
    ON dbo.TB_NOTIFICACAO_REGRA (EVENTO_GATILHO, ATIVO, VIGENCIA_INICIO)
    INCLUDE (ID, CODIGO, VERSAO_REGRA, TIPO_NOTIFICACAO);
GO

CREATE TABLE dbo.TB_NOTIFICACAO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_NOTIFICACAO PRIMARY KEY,
    REGRA_ID                 BIGINT NOT NULL,
    TIPO                     VARCHAR(60) NOT NULL,
    TITULO                   NVARCHAR(200) NOT NULL,
    MENSAGEM                 NVARCHAR(1000) NOT NULL,
    PRIORIDADE               VARCHAR(10) NOT NULL,
    STATUS                   VARCHAR(15) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_STATUS DEFAULT ('ATIVA'),

    ENTIDADE_TIPO            VARCHAR(30) NOT NULL,
    ENTIDADE_ID              NVARCHAR(100) NOT NULL,
    ROTEIRO_ID               UNIQUEIDENTIFIER NULL,
    VISITA_ID                BIGINT NULL,
    VISITA_PRODUTO_ID        BIGINT NULL,
    CHAVE_LOJA               NVARCHAR(100) NULL,

    CHAVE_DEDUPLICACAO       NVARCHAR(250) NOT NULL,
    ACAO_DESTINO             VARCHAR(80) NOT NULL,
    DESTINO_JSON             NVARCHAR(MAX) NOT NULL,
    ACOES_JSON               NVARCHAR(MAX) NOT NULL,
    COD_FUNC_ORIGEM          INT NULL,
    EVENTO_ORIGEM_ID         UNIQUEIDENTIFIER NOT NULL,
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,

    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    DISPONIVEL_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_DISPONIVEL_EM_UTC DEFAULT (SYSUTCDATETIME()),
    EXPIRA_EM_UTC            DATETIME2(3) NULL,
    RESOLVIDA_EM_UTC         DATETIME2(3) NULL,
    RESOLVIDA_POR            INT NULL,
    MOTIVO_RESOLUCAO         VARCHAR(60) NULL,
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT FK_TB_NOTIFICACAO_REGRA
        FOREIGN KEY (REGRA_ID) REFERENCES dbo.TB_NOTIFICACAO_REGRA(ID),
    CONSTRAINT FK_TB_NOTIFICACAO_ROTEIRO
        FOREIGN KEY (ROTEIRO_ID) REFERENCES dbo.ROTEIROS_MAPA(ID),
    CONSTRAINT FK_TB_NOTIFICACAO_VISITA
        FOREIGN KEY (VISITA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT FK_TB_NOTIFICACAO_VISITA_PRODUTO
        FOREIGN KEY (VISITA_PRODUTO_ID) REFERENCES dbo.TB_VISITA_PRODUTO(ID),
    CONSTRAINT UQ_TB_NOTIFICACAO_DEDUPLICACAO
        UNIQUE (CHAVE_DEDUPLICACAO),
    CONSTRAINT CK_TB_NOTIFICACAO_PRIORIDADE
        CHECK (PRIORIDADE IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_TB_NOTIFICACAO_STATUS
        CHECK (STATUS IN ('ATIVA', 'RESOLVIDA', 'CANCELADA', 'EXPIRADA')),
    CONSTRAINT CK_TB_NOTIFICACAO_ENTIDADE
        CHECK (ENTIDADE_TIPO IN (
            'ROTEIRO', 'VISITA', 'VISITA_PRODUTO',
            'ACOMPANHAMENTO', 'CHECKIN'
        )),
    CONSTRAINT CK_TB_NOTIFICACAO_JSON
        CHECK (ISJSON(DESTINO_JSON) = 1 AND ISJSON(ACOES_JSON) = 1),
    CONSTRAINT CK_TB_NOTIFICACAO_JANELA
        CHECK (EXPIRA_EM_UTC IS NULL OR EXPIRA_EM_UTC > CRIADO_EM_UTC),
    CONSTRAINT CK_TB_NOTIFICACAO_RESOLUCAO
        CHECK (
            STATUS = 'ATIVA' OR
            RESOLVIDA_EM_UTC IS NOT NULL
        )
);

CREATE INDEX IX_TB_NOTIFICACAO_STATUS_DATA
    ON dbo.TB_NOTIFICACAO (STATUS, DISPONIVEL_EM_UTC DESC)
    INCLUDE (ID, TIPO, PRIORIDADE, EXPIRA_EM_UTC, ENTIDADE_TIPO, ENTIDADE_ID);

CREATE INDEX IX_TB_NOTIFICACAO_VISITA
    ON dbo.TB_NOTIFICACAO (VISITA_ID, STATUS, CRIADO_EM_UTC DESC)
    INCLUDE (ID, TIPO, VISITA_PRODUTO_ID);

CREATE INDEX IX_TB_NOTIFICACAO_ROTEIRO
    ON dbo.TB_NOTIFICACAO (ROTEIRO_ID, STATUS, CRIADO_EM_UTC DESC)
    INCLUDE (ID, TIPO, VISITA_ID);

CREATE INDEX IX_TB_NOTIFICACAO_LOJA
    ON dbo.TB_NOTIFICACAO (CHAVE_LOJA, CRIADO_EM_UTC DESC)
    INCLUDE (ID, TIPO, STATUS, PRIORIDADE);

CREATE INDEX IX_TB_NOTIFICACAO_EVENTO_ORIGEM
    ON dbo.TB_NOTIFICACAO (EVENTO_ORIGEM_ID)
    INCLUDE (ID, REGRA_ID, TIPO, STATUS);
GO

CREATE TABLE dbo.TB_NOTIFICACAO_USUARIO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_NOTIFICACAO_USUARIO PRIMARY KEY,
    NOTIFICACAO_ID           BIGINT NOT NULL,
    COD_FUNC_DESTINATARIO    INT NOT NULL,
    STATUS                   VARCHAR(15) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_STATUS DEFAULT ('NOVA'),
    PRIMEIRA_ENTREGA_EM_UTC  DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_PRIMEIRA_ENTREGA DEFAULT (SYSUTCDATETIME()),
    ULTIMA_ENTREGA_EM_UTC    DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_ULTIMA_ENTREGA DEFAULT (SYSUTCDATETIME()),
    QTD_ENTREGAS             SMALLINT NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_QTD_ENTREGAS DEFAULT (1),
    VISUALIZADA_EM_UTC       DATETIME2(3) NULL,
    LIDA_EM_UTC              DATETIME2(3) NULL,
    CIENCIA_EM_UTC           DATETIME2(3) NULL,
    ADIADA_ATE_EM_UTC        DATETIME2(3) NULL,
    QTD_ADIAMENTOS           SMALLINT NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_QTD_ADIAMENTOS DEFAULT (0),
    RESOLVIDA_EM_UTC         DATETIME2(3) NULL,
    ARQUIVADA_EM_UTC         DATETIME2(3) NULL,
    ACAO_EXECUTADA           VARCHAR(80) NULL,
    ACAO_EXECUTADA_EM_UTC    DATETIME2(3) NULL,
    ESCALADA_EM_UTC          DATETIME2(3) NULL,
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_NOTIFICACAO_USUARIO_ATUALIZADO DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR           INT NOT NULL,
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT FK_TB_NOTIFICACAO_USUARIO_NOTIFICACAO
        FOREIGN KEY (NOTIFICACAO_ID) REFERENCES dbo.TB_NOTIFICACAO(ID),
    CONSTRAINT UQ_TB_NOTIFICACAO_USUARIO
        UNIQUE (NOTIFICACAO_ID, COD_FUNC_DESTINATARIO),
    CONSTRAINT CK_TB_NOTIFICACAO_USUARIO_STATUS
        CHECK (STATUS IN (
            'NOVA', 'VISUALIZADA', 'LIDA', 'ADIADA',
            'RESOLVIDA', 'ARQUIVADA', 'CANCELADA'
        )),
    CONSTRAINT CK_TB_NOTIFICACAO_USUARIO_CONTADORES
        CHECK (QTD_ENTREGAS > 0 AND QTD_ADIAMENTOS >= 0),
    CONSTRAINT CK_TB_NOTIFICACAO_USUARIO_ADIADA
        CHECK (
            STATUS <> 'ADIADA' OR ADIADA_ATE_EM_UTC IS NOT NULL
        )
);

CREATE INDEX IX_TB_NOTIFICACAO_USUARIO_CAIXA
    ON dbo.TB_NOTIFICACAO_USUARIO
        (COD_FUNC_DESTINATARIO, STATUS, ULTIMA_ENTREGA_EM_UTC DESC)
    INCLUDE (
        NOTIFICACAO_ID, LIDA_EM_UTC, ADIADA_ATE_EM_UTC,
        QTD_ENTREGAS, VISUALIZADA_EM_UTC
    );

CREATE INDEX IX_TB_NOTIFICACAO_USUARIO_NAO_LIDA
    ON dbo.TB_NOTIFICACAO_USUARIO
        (COD_FUNC_DESTINATARIO, ULTIMA_ENTREGA_EM_UTC DESC)
    INCLUDE (NOTIFICACAO_ID, STATUS)
    WHERE LIDA_EM_UTC IS NULL;

CREATE INDEX IX_TB_NOTIFICACAO_USUARIO_ADIADA
    ON dbo.TB_NOTIFICACAO_USUARIO (ADIADA_ATE_EM_UTC)
    INCLUDE (ID, NOTIFICACAO_ID, COD_FUNC_DESTINATARIO)
    WHERE STATUS = 'ADIADA';
GO

CREATE TABLE dbo.TB_VISITA_ACOMPANHAMENTO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_VISITA_ACOMPANHAMENTO PRIMARY KEY,
    VISITA_ID                BIGINT NOT NULL,
    VISITA_PRODUTO_ID        BIGINT NULL,
    NOTIFICACAO_ORIGEM_ID    BIGINT NULL,
    TIPO                     VARCHAR(30) NOT NULL,
    ACAO                     VARCHAR(50) NOT NULL,
    STATUS                   VARCHAR(20) NOT NULL
        CONSTRAINT DF_TB_VISITA_ACOMPANHAMENTO_STATUS DEFAULT ('ABERTO'),
    OBSERVACAO               NVARCHAR(2000) NOT NULL,
    EVIDENCIA_JSON           NVARCHAR(MAX) NULL,
    PROXIMA_ACAO_EM_UTC      DATETIME2(3) NULL,
    REALIZADO_EM_UTC         DATETIME2(3) NULL,
    RESULTADO                VARCHAR(50) NULL,
    COD_FUNC_RESPONSAVEL     INT NULL,
    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_ACOMPANHAMENTO_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),
    CRIADO_POR               INT NOT NULL,
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_VISITA_ACOMPANHAMENTO_ATUALIZADO DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_POR           INT NOT NULL,
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT FK_TB_VISITA_ACOMPANHAMENTO_VISITA
        FOREIGN KEY (VISITA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT FK_TB_VISITA_ACOMPANHAMENTO_PRODUTO
        FOREIGN KEY (VISITA_PRODUTO_ID) REFERENCES dbo.TB_VISITA_PRODUTO(ID),
    CONSTRAINT FK_TB_VISITA_ACOMPANHAMENTO_NOTIFICACAO
        FOREIGN KEY (NOTIFICACAO_ORIGEM_ID) REFERENCES dbo.TB_NOTIFICACAO(ID),
    CONSTRAINT CK_TB_VISITA_ACOMPANHAMENTO_TIPO
        CHECK (TIPO IN (
            'CONTATO', 'COMENTARIO_SUPERIOR', 'LEMBRETE_ADIADO',
            'VALIDACAO_AUTOMATICA', 'REAGENDAMENTO_CONTATO',
            'SEM_CONTINUIDADE'
        )),
    CONSTRAINT CK_TB_VISITA_ACOMPANHAMENTO_STATUS
        CHECK (STATUS IN ('ABERTO', 'AGENDADO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT CK_TB_VISITA_ACOMPANHAMENTO_EVIDENCIA
        CHECK (EVIDENCIA_JSON IS NULL OR ISJSON(EVIDENCIA_JSON) = 1)
);

CREATE INDEX IX_TB_VISITA_ACOMPANHAMENTO_VISITA_DATA
    ON dbo.TB_VISITA_ACOMPANHAMENTO (VISITA_ID, CRIADO_EM_UTC DESC)
    INCLUDE (ID, VISITA_PRODUTO_ID, TIPO, STATUS, CRIADO_POR);

CREATE INDEX IX_TB_VISITA_ACOMPANHAMENTO_PRODUTO_STATUS
    ON dbo.TB_VISITA_ACOMPANHAMENTO
        (VISITA_PRODUTO_ID, STATUS, PROXIMA_ACAO_EM_UTC)
    INCLUDE (ID, TIPO, COD_FUNC_RESPONSAVEL);

CREATE INDEX IX_TB_VISITA_ACOMPANHAMENTO_RESP_DATA
    ON dbo.TB_VISITA_ACOMPANHAMENTO
        (COD_FUNC_RESPONSAVEL, STATUS, PROXIMA_ACAO_EM_UTC)
    INCLUDE (ID, VISITA_ID, VISITA_PRODUTO_ID);
GO

/* -------------------------------------------------------------------------
   Outbox, histórico e auditoria append-only
   ------------------------------------------------------------------------- */

CREATE TABLE dbo.TB_EVENTO_OUTBOX (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_EVENTO_OUTBOX PRIMARY KEY,
    EVENTO_ID                UNIQUEIDENTIFIER NOT NULL,
    TIPO_EVENTO              VARCHAR(80) NOT NULL,
    AGREGADO_TIPO            VARCHAR(30) NOT NULL,
    AGREGADO_ID              NVARCHAR(100) NOT NULL,
    PAYLOAD_JSON             NVARCHAR(MAX) NOT NULL,
    CHAVE_DEDUPLICACAO       NVARCHAR(250) NULL,
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,
    OCORRIDO_EM_UTC          DATETIME2(3) NOT NULL,
    DISPONIVEL_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_EVENTO_OUTBOX_DISPONIVEL DEFAULT (SYSUTCDATETIME()),
    STATUS                   VARCHAR(15) NOT NULL
        CONSTRAINT DF_TB_EVENTO_OUTBOX_STATUS DEFAULT ('PENDENTE'),
    TENTATIVAS               SMALLINT NOT NULL
        CONSTRAINT DF_TB_EVENTO_OUTBOX_TENTATIVAS DEFAULT (0),
    BLOQUEADO_ATE_EM_UTC     DATETIME2(3) NULL,
    BLOQUEADO_POR_WORKER     VARCHAR(100) NULL,
    PROCESSADO_EM_UTC        DATETIME2(3) NULL,
    ULTIMO_ERRO              NVARCHAR(2000) NULL,
    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_EVENTO_OUTBOX_CRIADO_EM_UTC DEFAULT (SYSUTCDATETIME()),

    CONSTRAINT UQ_TB_EVENTO_OUTBOX_EVENTO UNIQUE (EVENTO_ID),
    CONSTRAINT CK_TB_EVENTO_OUTBOX_PAYLOAD CHECK (ISJSON(PAYLOAD_JSON) = 1),
    CONSTRAINT CK_TB_EVENTO_OUTBOX_STATUS
        CHECK (STATUS IN ('PENDENTE', 'PROCESSANDO', 'PROCESSADO', 'ERRO')),
    CONSTRAINT CK_TB_EVENTO_OUTBOX_TENTATIVAS CHECK (TENTATIVAS >= 0)
);

CREATE INDEX IX_TB_EVENTO_OUTBOX_PROCESSAMENTO
    ON dbo.TB_EVENTO_OUTBOX (STATUS, DISPONIVEL_EM_UTC, ID)
    INCLUDE (TIPO_EVENTO, TENTATIVAS, BLOQUEADO_ATE_EM_UTC);

CREATE INDEX IX_TB_EVENTO_OUTBOX_AGREGADO
    ON dbo.TB_EVENTO_OUTBOX (AGREGADO_TIPO, AGREGADO_ID, OCORRIDO_EM_UTC DESC)
    INCLUDE (EVENTO_ID, TIPO_EVENTO, STATUS, CORRELATION_ID);

CREATE UNIQUE INDEX UX_TB_EVENTO_OUTBOX_DEDUPLICACAO
    ON dbo.TB_EVENTO_OUTBOX (CHAVE_DEDUPLICACAO)
    WHERE CHAVE_DEDUPLICACAO IS NOT NULL;
GO

CREATE TABLE dbo.TB_COMANDO_IDEMPOTENCIA (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_COMANDO_IDEMPOTENCIA PRIMARY KEY,
    COD_FUNC_USUARIO         INT NOT NULL,
    ESCOPO                   VARCHAR(80) NOT NULL,
    CHAVE_IDEMPOTENCIA       VARCHAR(100) NOT NULL,
    METODO_HTTP              VARCHAR(10) NOT NULL,
    CAMINHO_HTTP             NVARCHAR(500) NOT NULL,
    REQUEST_HASH             CHAR(64) NOT NULL,
    STATUS                   VARCHAR(15) NOT NULL
        CONSTRAINT DF_TB_COMANDO_IDEMPOTENCIA_STATUS DEFAULT ('PROCESSANDO'),
    RESPONSE_STATUS          SMALLINT NULL,
    RESPONSE_JSON            NVARCHAR(MAX) NULL,
    ERRO_CODIGO              VARCHAR(80) NULL,
    BLOQUEADO_ATE_EM_UTC     DATETIME2(3) NULL,
    CRIADO_EM_UTC            DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_COMANDO_IDEMPOTENCIA_CRIADO DEFAULT (SYSUTCDATETIME()),
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_COMANDO_IDEMPOTENCIA_ATUALIZADO DEFAULT (SYSUTCDATETIME()),
    EXPIRA_EM_UTC            DATETIME2(3) NOT NULL,
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT UQ_TB_COMANDO_IDEMPOTENCIA_CHAVE
        UNIQUE (COD_FUNC_USUARIO, ESCOPO, CHAVE_IDEMPOTENCIA),
    CONSTRAINT CK_TB_COMANDO_IDEMPOTENCIA_STATUS
        CHECK (STATUS IN ('PROCESSANDO', 'CONCLUIDO', 'ERRO')),
    CONSTRAINT CK_TB_COMANDO_IDEMPOTENCIA_METODO
        CHECK (METODO_HTTP IN ('POST', 'PUT', 'PATCH', 'DELETE')),
    CONSTRAINT CK_TB_COMANDO_IDEMPOTENCIA_RESPONSE
        CHECK (RESPONSE_JSON IS NULL OR ISJSON(RESPONSE_JSON) = 1),
    CONSTRAINT CK_TB_COMANDO_IDEMPOTENCIA_EXPIRACAO
        CHECK (EXPIRA_EM_UTC > CRIADO_EM_UTC)
);

CREATE INDEX IX_TB_COMANDO_IDEMPOTENCIA_EXPIRACAO
    ON dbo.TB_COMANDO_IDEMPOTENCIA (EXPIRA_EM_UTC, STATUS)
    INCLUDE (ID, COD_FUNC_USUARIO, ESCOPO);

CREATE INDEX IX_TB_COMANDO_IDEMPOTENCIA_PROCESSANDO
    ON dbo.TB_COMANDO_IDEMPOTENCIA (STATUS, BLOQUEADO_ATE_EM_UTC)
    INCLUDE (ID, COD_FUNC_USUARIO, ESCOPO, CHAVE_IDEMPOTENCIA);
GO

CREATE TABLE dbo.TB_JOB_CONTROLE (
    CODIGO                   VARCHAR(80) NOT NULL
        CONSTRAINT PK_TB_JOB_CONTROLE PRIMARY KEY,
    DESCRICAO                NVARCHAR(300) NOT NULL,
    INTERVALO_SEGUNDOS       INT NOT NULL,
    ATIVO                    BIT NOT NULL
        CONSTRAINT DF_TB_JOB_CONTROLE_ATIVO DEFAULT (0),
    PROXIMA_EXECUCAO_EM_UTC  DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_JOB_CONTROLE_PROXIMA DEFAULT (SYSUTCDATETIME()),
    BLOQUEADO_ATE_EM_UTC     DATETIME2(3) NULL,
    BLOQUEADO_POR_WORKER     VARCHAR(100) NULL,
    ULTIMO_INICIO_EM_UTC     DATETIME2(3) NULL,
    ULTIMO_FIM_EM_UTC        DATETIME2(3) NULL,
    ULTIMO_STATUS            VARCHAR(15) NULL,
    ULTIMO_ERRO              NVARCHAR(2000) NULL,
    ATUALIZADO_EM_UTC        DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_JOB_CONTROLE_ATUALIZADO DEFAULT (SYSUTCDATETIME()),
    VERSAO_LINHA             ROWVERSION,

    CONSTRAINT CK_TB_JOB_CONTROLE_INTERVALO
        CHECK (INTERVALO_SEGUNDOS BETWEEN 5 AND 604800),
    CONSTRAINT CK_TB_JOB_CONTROLE_STATUS
        CHECK (
            ULTIMO_STATUS IS NULL OR
            ULTIMO_STATUS IN ('EXECUTANDO', 'SUCESSO', 'ERRO', 'IGNORADO')
        )
);

CREATE INDEX IX_TB_JOB_CONTROLE_FILA
    ON dbo.TB_JOB_CONTROLE (ATIVO, PROXIMA_EXECUCAO_EM_UTC)
    INCLUDE (CODIGO, INTERVALO_SEGUNDOS, BLOQUEADO_ATE_EM_UTC);
GO

CREATE TABLE dbo.TB_JOB_EXECUCAO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_JOB_EXECUCAO PRIMARY KEY,
    EXECUCAO_ID              UNIQUEIDENTIFIER NOT NULL,
    JOB_CODIGO               VARCHAR(80) NOT NULL,
    WORKER_ID                VARCHAR(100) NOT NULL,
    STATUS                   VARCHAR(15) NOT NULL,
    INICIADO_EM_UTC          DATETIME2(3) NOT NULL,
    FINALIZADO_EM_UTC        DATETIME2(3) NULL,
    ITENS_LIDOS              INT NOT NULL
        CONSTRAINT DF_TB_JOB_EXECUCAO_LIDOS DEFAULT (0),
    ITENS_PROCESSADOS        INT NOT NULL
        CONSTRAINT DF_TB_JOB_EXECUCAO_PROCESSADOS DEFAULT (0),
    ITENS_ERRO               INT NOT NULL
        CONSTRAINT DF_TB_JOB_EXECUCAO_ERRO DEFAULT (0),
    ERRO                     NVARCHAR(2000) NULL,
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,

    CONSTRAINT FK_TB_JOB_EXECUCAO_CONTROLE
        FOREIGN KEY (JOB_CODIGO) REFERENCES dbo.TB_JOB_CONTROLE(CODIGO),
    CONSTRAINT UQ_TB_JOB_EXECUCAO_ID UNIQUE (EXECUCAO_ID),
    CONSTRAINT CK_TB_JOB_EXECUCAO_STATUS
        CHECK (STATUS IN ('EXECUTANDO', 'SUCESSO', 'ERRO', 'IGNORADO')),
    CONSTRAINT CK_TB_JOB_EXECUCAO_CONTADORES
        CHECK (
            ITENS_LIDOS >= 0 AND
            ITENS_PROCESSADOS >= 0 AND
            ITENS_ERRO >= 0
        ),
    CONSTRAINT CK_TB_JOB_EXECUCAO_PERIODO
        CHECK (
            FINALIZADO_EM_UTC IS NULL OR
            FINALIZADO_EM_UTC >= INICIADO_EM_UTC
        )
);

CREATE INDEX IX_TB_JOB_EXECUCAO_JOB_DATA
    ON dbo.TB_JOB_EXECUCAO (JOB_CODIGO, INICIADO_EM_UTC DESC)
    INCLUDE (STATUS, FINALIZADO_EM_UTC, ITENS_PROCESSADOS, ITENS_ERRO);

CREATE INDEX IX_TB_JOB_EXECUCAO_CORRELATION
    ON dbo.TB_JOB_EXECUCAO (CORRELATION_ID)
    INCLUDE (JOB_CODIGO, STATUS, INICIADO_EM_UTC);
GO

CREATE TABLE dbo.TB_HISTORICO_VISITA (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_HISTORICO_VISITA PRIMARY KEY,
    VISITA_ID                BIGINT NOT NULL,
    VISITA_PRODUTO_ID        BIGINT NULL,
    CHECKIN_ID               BIGINT NULL,
    NOTIFICACAO_ID           BIGINT NULL,
    TIPO_EVENTO              VARCHAR(80) NOT NULL,
    STATUS_ANTERIOR          VARCHAR(30) NULL,
    STATUS_NOVO              VARCHAR(30) NULL,
    DADOS_ANTERIORES_JSON    NVARCHAR(MAX) NULL,
    DADOS_NOVOS_JSON         NVARCHAR(MAX) NULL,
    MOTIVO                   NVARCHAR(1000) NULL,
    COD_FUNC_ATOR            INT NULL,
    ORIGEM                   VARCHAR(20) NOT NULL,
    OCORRIDO_EM_UTC          DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_HISTORICO_VISITA_OCORRIDO DEFAULT (SYSUTCDATETIME()),
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,
    REQUEST_ID               UNIQUEIDENTIFIER NULL,
    IP_ADDRESS               VARCHAR(45) NULL,
    USER_AGENT               NVARCHAR(500) NULL,

    CONSTRAINT FK_TB_HISTORICO_VISITA_VISITA
        FOREIGN KEY (VISITA_ID) REFERENCES dbo.TB_VISITA_TRATATIVA(ID),
    CONSTRAINT FK_TB_HISTORICO_VISITA_PRODUTO
        FOREIGN KEY (VISITA_PRODUTO_ID) REFERENCES dbo.TB_VISITA_PRODUTO(ID),
    CONSTRAINT FK_TB_HISTORICO_VISITA_CHECKIN
        FOREIGN KEY (CHECKIN_ID) REFERENCES dbo.TB_VISITA_CHECKIN(ID),
    CONSTRAINT FK_TB_HISTORICO_VISITA_NOTIFICACAO
        FOREIGN KEY (NOTIFICACAO_ID) REFERENCES dbo.TB_NOTIFICACAO(ID),
    CONSTRAINT CK_TB_HISTORICO_VISITA_ORIGEM
        CHECK (ORIGEM IN ('USUARIO', 'SISTEMA', 'JOB', 'INTEGRACAO', 'ADMIN')),
    CONSTRAINT CK_TB_HISTORICO_VISITA_JSON
        CHECK (
            (DADOS_ANTERIORES_JSON IS NULL OR ISJSON(DADOS_ANTERIORES_JSON) = 1) AND
            (DADOS_NOVOS_JSON IS NULL OR ISJSON(DADOS_NOVOS_JSON) = 1)
        )
);

CREATE INDEX IX_TB_HISTORICO_VISITA_TIMELINE
    ON dbo.TB_HISTORICO_VISITA (VISITA_ID, OCORRIDO_EM_UTC DESC, ID DESC)
    INCLUDE (TIPO_EVENTO, STATUS_ANTERIOR, STATUS_NOVO, COD_FUNC_ATOR);

CREATE INDEX IX_TB_HISTORICO_VISITA_ATOR_DATA
    ON dbo.TB_HISTORICO_VISITA (COD_FUNC_ATOR, OCORRIDO_EM_UTC DESC)
    INCLUDE (VISITA_ID, TIPO_EVENTO, ORIGEM);

CREATE INDEX IX_TB_HISTORICO_VISITA_CORRELATION
    ON dbo.TB_HISTORICO_VISITA (CORRELATION_ID)
    INCLUDE (VISITA_ID, TIPO_EVENTO, OCORRIDO_EM_UTC);
GO

CREATE TABLE dbo.TB_AUDITORIA_ROTEIRO (
    ID                       BIGINT IDENTITY(1,1) NOT NULL
        CONSTRAINT PK_TB_AUDITORIA_ROTEIRO PRIMARY KEY,
    ROTEIRO_ID               UNIQUEIDENTIFIER NOT NULL,
    PARADA_ROTEIRO_ID        BIGINT NULL,
    TIPO_EVENTO              VARCHAR(80) NOT NULL,
    CAMPO_ALTERADO           VARCHAR(80) NULL,
    DADOS_ANTERIORES_JSON    NVARCHAR(MAX) NULL,
    DADOS_NOVOS_JSON         NVARCHAR(MAX) NULL,
    MOTIVO                   NVARCHAR(1000) NULL,
    PRIORIDADE_ANTERIOR      VARCHAR(10) NULL,
    PRIORIDADE_NOVA          VARCHAR(10) NULL,
    COD_FUNC_ATOR            INT NOT NULL,
    ORIGEM                   VARCHAR(20) NOT NULL,
    OCORRIDO_EM_UTC          DATETIME2(3) NOT NULL
        CONSTRAINT DF_TB_AUDITORIA_ROTEIRO_OCORRIDO DEFAULT (SYSUTCDATETIME()),
    CORRELATION_ID           UNIQUEIDENTIFIER NOT NULL,
    REQUEST_ID               UNIQUEIDENTIFIER NULL,
    IP_ADDRESS               VARCHAR(45) NULL,
    USER_AGENT               NVARCHAR(500) NULL,

    CONSTRAINT FK_TB_AUDITORIA_ROTEIRO_ROTEIRO
        FOREIGN KEY (ROTEIRO_ID) REFERENCES dbo.ROTEIROS_MAPA(ID),
    CONSTRAINT FK_TB_AUDITORIA_ROTEIRO_PARADA
        FOREIGN KEY (PARADA_ROTEIRO_ID) REFERENCES dbo.ROTEIRO_PARADAS_MAPA(ID),
    CONSTRAINT CK_TB_AUDITORIA_ROTEIRO_ORIGEM
        CHECK (ORIGEM IN ('USUARIO', 'SISTEMA', 'JOB', 'INTEGRACAO', 'ADMIN')),
    CONSTRAINT CK_TB_AUDITORIA_ROTEIRO_JSON
        CHECK (
            (DADOS_ANTERIORES_JSON IS NULL OR ISJSON(DADOS_ANTERIORES_JSON) = 1) AND
            (DADOS_NOVOS_JSON IS NULL OR ISJSON(DADOS_NOVOS_JSON) = 1)
        ),
    CONSTRAINT CK_TB_AUDITORIA_ROTEIRO_PRIORIDADE_ANTERIOR
        CHECK (
            PRIORIDADE_ANTERIOR IS NULL OR
            PRIORIDADE_ANTERIOR IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA')
        ),
    CONSTRAINT CK_TB_AUDITORIA_ROTEIRO_PRIORIDADE_NOVA
        CHECK (
            PRIORIDADE_NOVA IS NULL OR
            PRIORIDADE_NOVA IN ('BAIXA', 'NORMAL', 'ALTA', 'CRITICA')
        )
);

CREATE INDEX IX_TB_AUDITORIA_ROTEIRO_TIMELINE
    ON dbo.TB_AUDITORIA_ROTEIRO (ROTEIRO_ID, OCORRIDO_EM_UTC DESC, ID DESC)
    INCLUDE (PARADA_ROTEIRO_ID, TIPO_EVENTO, CAMPO_ALTERADO, COD_FUNC_ATOR);

CREATE INDEX IX_TB_AUDITORIA_ROTEIRO_ATOR_DATA
    ON dbo.TB_AUDITORIA_ROTEIRO (COD_FUNC_ATOR, OCORRIDO_EM_UTC DESC)
    INCLUDE (ROTEIRO_ID, TIPO_EVENTO, ORIGEM);

CREATE INDEX IX_TB_AUDITORIA_ROTEIRO_CORRELATION
    ON dbo.TB_AUDITORIA_ROTEIRO (CORRELATION_ID)
    INCLUDE (ROTEIRO_ID, TIPO_EVENTO, OCORRIDO_EM_UTC);
GO

/* Impede sobrescrita da trilha. Expurgo autorizado exige procedimento
   administrativo próprio e desativação explícita do trigger. */
CREATE OR ALTER TRIGGER dbo.TR_TB_HISTORICO_VISITA_APPEND_ONLY
ON dbo.TB_HISTORICO_VISITA
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51020, 'TB_HISTORICO_VISITA é append-only; UPDATE e DELETE não são permitidos.', 1;
END;
GO

CREATE OR ALTER TRIGGER dbo.TR_TB_AUDITORIA_ROTEIRO_APPEND_ONLY
ON dbo.TB_AUDITORIA_ROTEIRO
INSTEAD OF UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    THROW 51021, 'TB_AUDITORIA_ROTEIRO é append-only; UPDATE e DELETE não são permitidos.', 1;
END;
GO
