USE [TESTE];
GO

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
GO

/* Este arquivo é somente leitura. Resultado esperado: nenhuma linha nas
   consultas de inconsistência e todas as tabelas/constraints listadas. */

SELECT
    t.name AS TABELA,
    SUM(p.rows) AS LINHAS
FROM sys.tables AS t
INNER JOIN sys.partitions AS p
    ON p.object_id = t.object_id
   AND p.index_id IN (0, 1)
WHERE t.name IN (
    'TB_PRODUTO_FOCO',
    'TB_PRODUTO_REGRA_ACOMPANHAMENTO',
    'TB_VISITA_TRATATIVA',
    'TB_VISITA_CHECKIN',
    'TB_VISITA_PRODUTO',
    'TB_VISITA_REAGENDAMENTO',
    'TB_VISITA_ACOMPANHAMENTO',
    'TB_NOTIFICACAO_REGRA',
    'TB_NOTIFICACAO',
    'TB_NOTIFICACAO_USUARIO',
    'TB_EVENTO_OUTBOX',
    'TB_COMANDO_IDEMPOTENCIA',
    'TB_JOB_CONTROLE',
    'TB_JOB_EXECUCAO',
    'TB_HISTORICO_VISITA',
    'TB_AUDITORIA_ROTEIRO'
)
GROUP BY t.name
ORDER BY t.name;

SELECT
    OBJECT_NAME(parent_object_id) AS TABELA,
    name AS CONSTRAINT_NAO_CONFIAVEL
FROM sys.check_constraints
WHERE is_not_trusted = 1
  AND OBJECT_NAME(parent_object_id) LIKE 'TB[_]%';

SELECT
    OBJECT_NAME(parent_object_id) AS TABELA,
    name AS FK_NAO_CONFIAVEL
FROM sys.foreign_keys
WHERE is_not_trusted = 1
  AND OBJECT_NAME(parent_object_id) LIKE 'TB[_]%';

SELECT
    PARADA_ROTEIRO_ID,
    COUNT(*) AS QUANTIDADE_ATUAIS
FROM dbo.TB_VISITA_TRATATIVA
WHERE EH_ATUAL = 1
GROUP BY PARADA_ROTEIRO_ID
HAVING COUNT(*) > 1;

SELECT
    VISITA_ID,
    PRODUTO_ID,
    COUNT(*) AS DUPLICADOS
FROM dbo.TB_VISITA_PRODUTO
GROUP BY VISITA_ID, PRODUTO_ID
HAVING COUNT(*) > 1;

SELECT
    CHAVE_DEDUPLICACAO,
    COUNT(*) AS DUPLICADOS
FROM dbo.TB_NOTIFICACAO
GROUP BY CHAVE_DEDUPLICACAO
HAVING COUNT(*) > 1;

SELECT
    NOTIFICACAO_ID,
    COD_FUNC_DESTINATARIO,
    COUNT(*) AS DUPLICADOS
FROM dbo.TB_NOTIFICACAO_USUARIO
GROUP BY NOTIFICACAO_ID, COD_FUNC_DESTINATARIO
HAVING COUNT(*) > 1;

SELECT
    v.ID AS VISITA_REALIZADA_INCOMPLETA,
    COUNT_BIG(*) AS PRODUTOS_PENDENTES
FROM dbo.TB_VISITA_TRATATIVA AS v
INNER JOIN dbo.TB_VISITA_PRODUTO AS p
    ON p.VISITA_ID = v.ID
WHERE v.STATUS = 'REALIZADA'
  AND p.ATIVO = 1
  AND p.STATUS_TRATATIVA = 'PENDENTE'
GROUP BY v.ID;

SELECT
    n.ID AS NOTIFICACAO_ATIVA_ENTIDADE_TERMINAL,
    n.TIPO,
    n.VISITA_ID,
    v.STATUS AS STATUS_VISITA
FROM dbo.TB_NOTIFICACAO AS n
INNER JOIN dbo.TB_VISITA_TRATATIVA AS v
    ON v.ID = n.VISITA_ID
WHERE n.STATUS = 'ATIVA'
  AND n.TIPO IN ('VISITA_PROXIMA', 'TRATATIVA_PENDENTE')
  AND v.STATUS IN ('REALIZADA', 'NAO_REALIZADA', 'REAGENDADA', 'CANCELADA');

SELECT
    v.ID AS VISITA_SEM_PRODUTO,
    v.ROTEIRO_ID,
    v.PARADA_ROTEIRO_ID,
    v.CHAVE_LOJA
FROM dbo.TB_VISITA_TRATATIVA AS v
WHERE v.STATUS <> 'CANCELADA'
  AND NOT EXISTS (
      SELECT 1
      FROM dbo.TB_VISITA_PRODUTO AS p
      WHERE p.VISITA_ID = v.ID
        AND p.ATIVO = 1
  );

SELECT
    p.CODIGO,
    p.NOME,
    p.ATIVO,
    r.PRAZO_DIAS,
    r.DIAS_UTEIS,
    r.ESTRATEGIA_VALIDACAO,
    r.VERSAO_REGRA
FROM dbo.TB_PRODUTO_FOCO AS p
LEFT JOIN dbo.TB_PRODUTO_REGRA_ACOMPANHAMENTO AS r
    ON r.PRODUTO_ID = p.ID
   AND r.ATIVO = 1
ORDER BY p.CODIGO;

SELECT
    CODIGO,
    VERSAO_REGRA,
    TIPO_NOTIFICACAO,
    EVENTO_GATILHO,
    PRIORIDADE_PADRAO,
    ATIVO
FROM dbo.TB_NOTIFICACAO_REGRA
ORDER BY CODIGO, VERSAO_REGRA DESC;

SELECT
    CODIGO,
    ATIVO,
    INTERVALO_SEGUNDOS,
    PROXIMA_EXECUCAO_EM_UTC,
    ULTIMO_STATUS,
    ULTIMO_ERRO
FROM dbo.TB_JOB_CONTROLE
ORDER BY CODIGO;
GO
