USE [TESTE];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.TB_JOB_CONTROLE', N'U') IS NOT NULL
    BEGIN
        UPDATE dbo.TB_JOB_CONTROLE
        SET
            ATIVO = 0,
            BLOQUEADO_ATE_EM_UTC = NULL,
            BLOQUEADO_POR_WORKER = NULL,
            ATUALIZADO_EM_UTC = SYSUTCDATETIME();
    END;

    IF OBJECT_ID(N'dbo.TB_NOTIFICACAO_REGRA', N'U') IS NOT NULL
    BEGIN
        UPDATE dbo.TB_NOTIFICACAO_REGRA
        SET
            ATIVO = 0,
            ATUALIZADO_EM_UTC = SYSUTCDATETIME(),
            ATUALIZADO_POR = 0
        WHERE ATIVO = 1;
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

SELECT
    CODIGO,
    ATIVO,
    ULTIMO_STATUS,
    ULTIMO_FIM_EM_UTC
FROM dbo.TB_JOB_CONTROLE
ORDER BY CODIGO;
GO
