USE [TESTE];
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

IF OBJECT_ID(N'dbo.TB_JOB_CONTROLE', N'U') IS NULL
    THROW 51060, 'Tabela dbo.TB_JOB_CONTROLE não encontrada.', 1;
GO

UPDATE dbo.TB_JOB_CONTROLE
SET
    ATIVO = 1,
    PROXIMA_EXECUCAO_EM_UTC = SYSUTCDATETIME(),
    BLOQUEADO_ATE_EM_UTC = NULL,
    BLOQUEADO_POR_WORKER = NULL,
    ULTIMO_ERRO = NULL,
    ATUALIZADO_EM_UTC = SYSUTCDATETIME()
WHERE CODIGO IN (
    'OUTBOX_DISPATCHER',
    'VISIT_UPCOMING',
    'VISIT_OVERDUE',
    'PRODUCT_EVOLUTION',
    'NOTIFICATION_RESURFACE',
    'NOTIFICATION_EXPIRATION',
    'CONSISTENCY_RECONCILER'
);

SELECT CODIGO, ATIVO, INTERVALO_SEGUNDOS, PROXIMA_EXECUCAO_EM_UTC
FROM dbo.TB_JOB_CONTROLE
ORDER BY CODIGO;
GO
