IF OBJECT_ID(N'TESTE.dbo.AUTH_LOGS_MAPA', N'U') IS NULL
BEGIN
    CREATE TABLE TESTE.dbo.AUTH_LOGS_MAPA (
        ID             BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        COD_FUNC       NVARCHAR(20) NULL,
        DATA_HORA      DATETIME2 NOT NULL CONSTRAINT DF_AUTH_LOGS_MAPA_DATA_HORA DEFAULT SYSDATETIME(),
        ACAO           VARCHAR(30) NOT NULL,
        METODO         VARCHAR(30) NULL,
        STATUS         VARCHAR(20) NOT NULL,
        IP_ADDRESS     VARCHAR(45) NULL,
        USER_AGENT     NVARCHAR(500) NULL,
        DETALHES       NVARCHAR(MAX) NULL
    );
END;
