IF OBJECT_ID(N'TESTE.dbo.ROTEIROS_MAPA', N'U') IS NULL
BEGIN
    CREATE TABLE TESTE.dbo.ROTEIROS_MAPA (
        ID                       UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ROTEIROS_MAPA PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
        REQUEST_ID               UNIQUEIDENTIFIER NOT NULL,
        COD_FUNC_RESPONSAVEL     INT NOT NULL,
        NOME_RESPONSAVEL         NVARCHAR(150) NOT NULL,
        CHAVE_SUPERVISAO         INT NOT NULL,
        DESC_SUPERVISAO          NVARCHAR(150) NULL,
        COD_FUNC_CRIADOR         INT NOT NULL,
        NOME_CRIADOR             NVARCHAR(150) NOT NULL,
        DATA_ROTEIRO             DATE NOT NULL,
        VERSAO                   INT NOT NULL,
        NOME                     NVARCHAR(250) NOT NULL,
        ORIGEM_NOME              NVARCHAR(250) NOT NULL,
        ORIGEM_LAT               FLOAT NOT NULL,
        ORIGEM_LNG               FLOAT NOT NULL,
        DESTINO_NOME             NVARCHAR(250) NULL,
        DESTINO_LAT              FLOAT NULL,
        DESTINO_LNG              FLOAT NULL,
        DISTANCIA_METROS         BIGINT NOT NULL,
        DESLOCAMENTO_MINUTOS     INT NOT NULL,
        VISITAS_MINUTOS          INT NOT NULL,
        MINUTOS_POR_VISITA       INT NOT NULL,
        GEOMETRIA_JSON           NVARCHAR(MAX) NOT NULL,
        CRIADO_EM                DATETIME2 NOT NULL CONSTRAINT DF_ROTEIROS_MAPA_CRIADO_EM DEFAULT SYSDATETIME(),
        CONSTRAINT CK_ROTEIROS_MAPA_VERSAO CHECK (VERSAO > 0),
        CONSTRAINT CK_ROTEIROS_MAPA_GEOMETRIA_JSON CHECK (ISJSON(GEOMETRIA_JSON) = 1),
        CONSTRAINT CK_ROTEIROS_MAPA_COORD_ORIGEM CHECK (ORIGEM_LAT BETWEEN -90 AND 90 AND ORIGEM_LNG BETWEEN -180 AND 180)
    );

    CREATE UNIQUE INDEX UX_ROTEIROS_MAPA_REQUEST_ID
        ON TESTE.dbo.ROTEIROS_MAPA (REQUEST_ID);
    CREATE UNIQUE INDEX UX_ROTEIROS_MAPA_RESP_DATA_VERSAO
        ON TESTE.dbo.ROTEIROS_MAPA (COD_FUNC_RESPONSAVEL, DATA_ROTEIRO, VERSAO);
    CREATE INDEX IX_ROTEIROS_MAPA_SUP_DATA
        ON TESTE.dbo.ROTEIROS_MAPA (CHAVE_SUPERVISAO, DATA_ROTEIRO DESC, CRIADO_EM DESC);
END;

IF OBJECT_ID(N'TESTE.dbo.ROTEIRO_PARADAS_MAPA', N'U') IS NULL
BEGIN
    CREATE TABLE TESTE.dbo.ROTEIRO_PARADAS_MAPA (
        ID                       BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ROTEIRO_PARADAS_MAPA PRIMARY KEY,
        ROTEIRO_ID               UNIQUEIDENTIFIER NOT NULL,
        ORDEM                    INT NOT NULL,
        CHAVE_LOJA               NVARCHAR(100) NOT NULL,
        COD_AG                   NVARCHAR(20) NULL,
        NOME                     NVARCHAR(250) NOT NULL,
        HORARIO                  NVARCHAR(20) NOT NULL,
        STATUS                   VARCHAR(20) NOT NULL,
        ENDERECO                 NVARCHAR(500) NULL,
        CEP_CONTEXTO             NVARCHAR(250) NULL,
        PRODUTO_FOCO             NVARCHAR(500) NOT NULL,
        FOCOS_JSON               NVARCHAR(MAX) NOT NULL,
        OPORTUNIDADES_JSON       NVARCHAR(MAX) NOT NULL,
        ULTIMA_VISITA            NVARCHAR(100) NULL,
        PROXIMA_ACAO             NVARCHAR(1000) NULL,
        LAT                      FLOAT NOT NULL,
        LNG                      FLOAT NOT NULL,
        CONSTRAINT FK_ROTEIRO_PARADAS_MAPA_ROTEIRO FOREIGN KEY (ROTEIRO_ID)
            REFERENCES TESTE.dbo.ROTEIROS_MAPA(ID),
        CONSTRAINT CK_ROTEIRO_PARADAS_MAPA_ORDEM CHECK (ORDEM > 0),
        CONSTRAINT CK_ROTEIRO_PARADAS_MAPA_FOCOS_JSON CHECK (ISJSON(FOCOS_JSON) = 1),
        CONSTRAINT CK_ROTEIRO_PARADAS_MAPA_OPORTUNIDADES_JSON CHECK (ISJSON(OPORTUNIDADES_JSON) = 1),
        CONSTRAINT CK_ROTEIRO_PARADAS_MAPA_COORD CHECK (LAT BETWEEN -90 AND 90 AND LNG BETWEEN -180 AND 180)
    );

    CREATE UNIQUE INDEX UX_ROTEIRO_PARADAS_MAPA_ORDEM
        ON TESTE.dbo.ROTEIRO_PARADAS_MAPA (ROTEIRO_ID, ORDEM);
END;

